<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.287">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="CillianMacAodh (Cillian McHugh)">
<meta name="dcterms.date" content="2019-08-03">
<meta name="description" content="Andreas Handel’s personal website.">

<title>Cillian McHugh - R Markdown Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//files/icon1.png" rel="icon" type="image/png">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  });
});
</script> 
  


<link rel="stylesheet" href="../../customstyle.css">
<meta name="twitter:title" content="Cillian McHugh - R Markdown Workshop">
<meta name="twitter:description" content="Materials from a workshop on using RMarkdown">
<meta name="twitter:creator" content="@cillianmacaodh">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Cillian McHugh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html" rel="" target="">
 <span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../music.html" rel="" target="">
 <span class="menu-text">Music</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../other.html" rel="" target="">
 <span class="menu-text">Other</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../rblog.html" rel="" target="">
 <span class="menu-text">R Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/cillianmacaodh" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#r-markdown-basics" id="toc-r-markdown-basics" class="nav-link" data-scroll-target="#r-markdown-basics">R Markdown Basics</a></li>
  <li><a href="#working-with-r" id="toc-working-with-r" class="nav-link" data-scroll-target="#working-with-r">Working with R</a>
  <ul class="collapse">
  <li><a href="#working-with-dataframes" id="toc-working-with-dataframes" class="nav-link" data-scroll-target="#working-with-dataframes">Working with dataframes</a>
  <ul class="collapse">
  <li><a href="#some-basics" id="toc-some-basics" class="nav-link" data-scroll-target="#some-basics">Some basics:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#statistical-tests" id="toc-statistical-tests" class="nav-link" data-scroll-target="#statistical-tests">Statistical tests</a></li>
  <li><a href="#running-a-t-test" id="toc-running-a-t-test" class="nav-link" data-scroll-target="#running-a-t-test">Running a t-test</a>
  <ul class="collapse">
  <li><a href="#t-test-transmission-and-mpg" id="toc-t-test-transmission-and-mpg" class="nav-link" data-scroll-target="#t-test-transmission-and-mpg">T-test: Transmission and MPG</a></li>
  </ul></li>
  <li><a href="#chi-square" id="toc-chi-square" class="nav-link" data-scroll-target="#chi-square">Chi-square</a></li>
  <li><a href="#anova-and-correlation" id="toc-anova-and-correlation" class="nav-link" data-scroll-target="#anova-and-correlation">ANOVA and Correlation</a></li>
  <li><a href="#tables" id="toc-tables" class="nav-link" data-scroll-target="#tables">Tables</a></li>
  <li><a href="#using-citations" id="toc-using-citations" class="nav-link" data-scroll-target="#using-citations">Using Citations</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R Markdown Workshop</h1>
</div>

<div>
  <div class="description">
    Materials from a workshop on using RMarkdown
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>CillianMacAodh (Cillian McHugh) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 3, 2019</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="background" class="level1">
<h1>Background</h1>
<p>This is an unusual post for me, I have avoided writing about R Markdown because there are so many resources already available on the topic (e.g., <a href="http://rmarkdown.rstudio.com/authoring_basics.html">here</a>, <a href="https://shiny.rstudio.com/articles/rmarkdown.html">here</a>, and <a href="http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html">here</a>). However, recently I ran a session on using RMarkdown for my colleagues in the <a href="http://www.ul.ie/csi-r/">Centre for Social Issues Research</a>. The aim of this was to demonstrate the usefulness of R Markdown (and hopefully convert a few people). For this session I created a set of resources<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> aimed at making the transition from SPSS to R Markdown a bit easier. The <em>statistics</em> content of these resources is mainly just some of the simpler standard tests taught to psychology undergraduate students.</p>
<p>The complete resources are available on <a href="https://osf.io/nyu4g/">this project page on the OSF</a>. The main purpose of the exercise was to provide people with the tools to create <a href="https://mfr.osf.io/render?url=https://osf.io/z6udg/?action=download%26mode=render">this pdf</a> using <a href="https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render">this R Markdown template</a>. My hope is that by using this template, SPSS users might make the tranistion to R, and R Markdown (with the help of the wonderful <a href="https://crsh.github.io/papaja_man/">papaja</a> package <span class="citation" data-cites="aust_papaja_2017">Aust (<a href="#ref-aust_papaja_2017" role="doc-biblioref">2017</a>)</span>).</p>
</section>
<section id="r-markdown-basics" class="level1">
<h1>R Markdown Basics</h1>
<p>I started off the workshop by going through some of the basics of R Markdown. When working with R Markdown, there are three types of text to be concerned with.</p>
<ol type="1">
<li><strong>Plain text</strong>: this is what you will use to write your manuscript. The formatting of this plain text is fairly straight forward (<a href="https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf">see this cheatsheet</a>)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
</ol>
<ol start="2" type="1">
<li><strong>Code chunks</strong>: these are denoted by three back ticks <code>```</code> at the top and the bottom of a chunk with commands in curly brackets in the title (on the same line as the firs set of back ticks). Code chunks allow you to run analyses without leaving your document. Output from code chunks can be included or omitted from your main output document.</li>
<li><strong>In-line code</strong>: this is denoted by a single back tick to begin a piece of code and a single back tick to close it <code>code goes here</code>.</li>
</ol>
<p>Each time you open a piece of code (a chunk or in-line code) you have to identify what language you want to code in. This is done by including the letter “r” in the curly brackets or immediately after the opening back tick.</p>
</section>
<section id="working-with-r" class="level1">
<h1>Working with R</h1>
<p>In order to show some of the basic functionality of R, I ran some analyses using the data sets that are built into R. This means that anyone should be able to reproduce the analyses conducted using the <a href="https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render">template</a> I provided (without needing to worry about loading data from other files). I also provided another <a href="https://mfr.osf.io/render?url=https://osf.io/6vz4e/?action=download%26mode=render">document</a> with an accompanying <a href="https://mfr.osf.io/render?url=https://osf.io/kub2w/?action=download%26mode=render">template</a> detailing the steps for inputting data into R. But this process is more prone to errors and if you are not familiar with R it can be a bit unintuitive.</p>
<section id="working-with-dataframes" class="level2">
<h2 class="anchored" data-anchor-id="working-with-dataframes">Working with dataframes</h2>
<p>A dataframe is structured much like an SPSS file. There are rows and columns, the columns are named and generally represent variables. The rows (can also be named) generally represent cases. You can have multiple data frames loaded with different names, although they are commonly saved as <code>df</code> (and these can be numbered <code>df1 df2 df3</code>. If your document/code is well organised, it can be useful have a generic name for dataframes that you are working with. This means that much of your code can be recycled (particularly if the variable names are the same - if you run repeated studies, or studies with only minor changes, you will find that there is massive scope for recycling code - both chunks and in-line)</p>
<section id="some-basics" class="level3">
<h3 class="anchored" data-anchor-id="some-basics">Some basics:</h3>
<ol type="1">
<li>The entire dataframe can be printed to the console by running the name of the data frame</li>
<li>The dollar sign can be used to call specific variables from the data frame i.e., <code>df$variable_name</code></li>
<li>A function has the form “function name” followed by parenthesis: <code>function_name()</code>.</li>
<li>The object that you want to run the function on goes in the parenthesis. e.g., if our dataframe was called <code>df</code>, and age was called <code>age</code> and we wanted to get the mean age we would run <code>mean(df$age)</code>.</li>
<li>Sometimes missing data denoted by <code>NA</code> can mess with some functions, to account for this it is helpful to include the argument <code>na.rm = TRUE</code> in the function, e.g., <code>mean(df$age, na.rm = TRUE)</code></li>
</ol>
<p>The <code>mtcars</code> dataset comes with R. For information on it simply type <code>help(mtcars)</code>. The variables of interest here are <code>am</code> (transmission; 0 = automatic, 1 = manual), <code>mpg</code> (miles per gallon), <code>qsec</code> (1/4 mile time). Below we practice a few simple functions to find out information about the dataset.</p>
<section id="example-code-and-output" class="level4">
<h4 class="anchored" data-anchor-id="example-code-and-output">Example code and output:</h4>
<ul>
<li>Load the <code>mtcars</code> dataset into an object called <code>df</code> using the command <code>df &lt;- mtcars</code></li>
<li>View the variable names associated with <code>df</code> by running <code>variable.names(df)</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"</code></pre>
</div>
</div>
<ul>
<li>The mean miles per gallon can be calculated using <code>mean(df$mpg)</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.09062</code></pre>
</div>
</div>
<ul>
<li>The standard deviation of the same variable is calculated using <code>sd(df$mpg)</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.026948</code></pre>
</div>
</div>
<ul>
<li>Or if you want to see basic descriptives use <code>descriptives(df$mpg)</code><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      mean       sd  min  max len
1 20.09062 6.026948 10.4 33.9  32</code></pre>
</div>
</div>
<ul>
<li>To index by a variable we use square brackets <code>[]</code> and the <code>which()</code> function.
<ul>
<li>The following command gets the mean miles per gallon for all cars with manual transmission:
<ul>
<li><code>mean(df$mpg[which(df$am==1)])</code></li>
</ul></li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.39231</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="statistical-tests" class="level1">
<h1>Statistical tests</h1>
<p>Now that we know some of the basics, we’ll try running some statistical tests.</p>
</section>
<section id="running-a-t-test" class="level1">
<h1>Running a t-test</h1>
<p>I’m going to use the <code>mtcars</code> dataset to illustrate how to run and write up a t-test, in such a way that:</p>
<ol type="a">
<li>there is no copy/paste error in reporting values; and</li>
<li>you can recycle code and text.</li>
</ol>
<p>In addition to <code>mpg</code> (miles per gallon), the other variable I am interested in is <code>am</code> (transmission; 0 = automatic, 1 = manual).<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>The question I’m going to look at is:</p>
<ol type="i">
<li>Is there a difference in miles per gallon depending on transmission?</li>
</ol>
<section id="t-test-transmission-and-mpg" class="level2">
<h2 class="anchored" data-anchor-id="t-test-transmission-and-mpg">T-test: Transmission and MPG</h2>
<ul>
<li>Load mtcars and save it in your environment using <code>df &lt;- mtcars</code></li>
<li>Create a new dataframe with a generic name e.g., <code>x</code> using the command: <code>x &lt;- df</code></li>
<li>This command runs the t-test and you can see the output in the console <code>t.test(x$mpg~x$am)</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x$mpg by x$am
t = -3.7671, df = 18.332, p-value = 0.001374
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -11.280194  -3.209684
sample estimates:
mean in group 0 mean in group 1 
       17.14737        24.39231 </code></pre>
</div>
</div>
<ul>
<li>The following code runs the t-test but saves the output as a list <code>t</code> that can be called later: <code>t &lt;- t.test(x$mpg~x$am)</code></li>
</ul>
<ul>
<li>As with dataframes, specific variables within a list can be called using the dollar sign</li>
<li>To call the p value simply type <code>t$p.value</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001373638</code></pre>
</div>
</div>
<ul>
<li>To call the t statistic, type <code>t$statistic</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        t 
-3.767123 </code></pre>
</div>
</div>
<ul>
<li>And to call the degrees of freedom, type <code>t$parameter</code></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      df 
18.33225 </code></pre>
</div>
</div>
<ul>
<li>Finally, to calculate the effect size and save it to an object type <code>td &lt;- cohensD(mpg~am, data=x)</code></li>
</ul>
<p>From the above we can call each value we need using in-line code to write up our results section as follows</p>
<section id="this-is-what-the-paragraph-will-look-like-in-your-rmd-document" class="level5">
<h5 class="anchored" data-anchor-id="this-is-what-the-paragraph-will-look-like-in-your-rmd-document">This is what the paragraph will look like in your Rmd document:</h5>
<p>An independent samples t-test revealed a significant difference in miles per gallon between cars with automatic transmission (<code>*M*</code> = <code>`r mean(x$mpg[which(x$am==0)])`</code>, <code>*SD*</code> = <code>`r sd(x$mpg[which(x$am==0)])`</code>), and cars with manual transmission, (<code>*M*</code> = <code>`r mean(x$mpg[which(x$am==1)])`</code>, <code>*SD*</code> = <code>`r sd(x$mpg[which(x$am==1)])`</code>), <code>*t*</code>(<code>`r t$parameter`</code>) = <code>`r t$statistic`</code>, <code>*p*</code> <code>`r paste(p_report(t$p.value))`</code>, <code>*d*</code> = <code>`r td</code>.</p>
</section>
<section id="the-above-syntax-will-return-the-following" class="level5">
<h5 class="anchored" data-anchor-id="the-above-syntax-will-return-the-following">The above syntax will return the following:</h5>
<p>An independent samples t-test revealed a significant difference in miles per gallon between cars with automatic transmission (<em>M</em> = 17.15, <em>SD</em> = 3.83), and cars with manual transmission, (<em>M</em> = 24.39, <em>SD</em> = 3.83), <em>t</em>(18.33) = -3.767, <em>p</em> = .001, <em>d</em> = 1.48.</p>
<p>If you want to run another t-test later on in your document you simply run it in a code chunk and create new objects (<code>t</code> and <code>td</code>) with the same names as before and you can use the same write up as above to report it.</p>
</section>
</section>
</section>
<section id="chi-square" class="level1">
<h1>Chi-square</h1>
<p>To illustrate a chi-squared test I will test if there is an association between engine type <code>vs</code> (0 = V-shaped, 1 = straight) and transmission type (0 = automatic, 1 = manual). Again this is to illustrate the code/write up - not a real test.</p>
<ul>
<li>First create a table using the command <code>table(x$am,x$vs)</code></li>
<li>Running a chi-squared test using <code>chisq.test(table(x$am,x$vs))</code> returns:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(x$am, x$vs)
X-squared = 0.34754, df = 1, p-value = 0.5555</code></pre>
</div>
</div>
<ul>
<li>As with the t-test, in order to report it using in-line code you need to save the test as an object e.g., <code>c</code> using <code>c &lt;- chisq.test(table(x$am,x$vs))</code></li>
<li>Save the effect size using <code>w &lt;- sqrt(c$statistic/(length(x$mpg)*c$parameter))</code></li>
<li>And calculate the observed power using <code>pw &lt;- pwr.chisq.test(w=w,N=length(x$mpg),df=(c$parameter),sig.level = .05)</code></li>
</ul>
<section id="report-using-the-following" class="level5">
<h5 class="anchored" data-anchor-id="report-using-the-following">Report using the following</h5>
<p>A chi-squared test for independence revealed no significant association between engine type and transmission type, <code>&amp;chi;^2^</code>(<code>`r c$parameter`</code>, <code>*N*</code> = <code>`r length(x$mpg)`</code>) = <code>`r c$statistic`</code>, <code>*p*</code> <code>`r paste(p_report(t$p.value))`</code>, <code>*V*</code> = <code>`r w</code>, the observed power was <code>`r pw$power`</code>.</p>
</section>
<section id="the-above-returns-the-following" class="level5">
<h5 class="anchored" data-anchor-id="the-above-returns-the-following">The above returns the following:</h5>
<p>A chi-squared test for independence revealed no significant association between engine type and transmission type, χ<sup>2</sup>(1, <em>N</em> = 32) = 0.348, <em>p</em> = .556 <em>V</em> = 0.1, the observed power was 0.09. (<a href="http://www.real-statistics.com/chi-square-and-f-distributions/effect-size-chi-square/">see this resource for effect size calculations for chi-squared tests</a>).</p>
</section>
</section>
<section id="anova-and-correlation" class="level1">
<h1>ANOVA and Correlation</h1>
<p>For details on the ANOVA check out the <a href="https://mfr.osf.io/render?url=https://osf.io/z6udg/?action=download%26mode=render">pdf</a> using the <a href="https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render">R Markdown template</a> on the OSF page.</p>
</section>
<section id="tables" class="level1">
<h1>Tables</h1>
<p>Again using the <code>mtcars</code> dataset, I’m going to make a few tables. Bear in mind that the code for these tables is designed to be used along with the <code>papaja</code> package and rendered to pdf, so the html tables in this post will not be formatted as correctly as they should be (refer to the resources on the OSF to see what it should look like).</p>
<ul>
<li>Firstly save <code>mtcars</code> as an object using <code>x &lt;- mtcars</code></li>
<li>We will make a table of engine type (V-shaped vs Straight) agains number of gears (3, 4, or 5) using <code>table(x$vs,x$gear)</code> which returns:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   
     3  4  5
  0 12  2  4
  1  3 10  1</code></pre>
</div>
</div>
<ul>
<li>This table is useful to us, but it doesn’t really sit well in our document</li>
<li>We can address this using the <code>apa_table()</code> function</li>
<li>Before using this function we need to create a matrix that can be passed through the function using the command <code>test &lt;- as.data.frame.matrix(table(x$vs,x$gear))</code></li>
<li>We can give names to the rows using <code>test &lt;-</code>rownames&lt;-<code>(test, c("V-shaped","Straight"))</code></li>
<li>And we can give names to the columns using <code>test &lt;-</code>colnames&lt;-<code>(test, c("3 gears","4 gears","5 gears"))</code></li>
<li>Finally we pass our object (matrix) <code>test</code> through the <code>apa_table()</code> function to render a table that will be embedded in our document</li>
<li>The code below will generate the Table&nbsp;@ref(tab:simpletable):</li>
</ul>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apa_table</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>   test</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>   , <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"l"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>   , <span class="at">caption =</span> <span class="st">"Engine type and number of gears"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>   , <span class="at">added_stub_head =</span> <span class="st">"Engine Type"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>   <span class="co">#, col_spanners = makespanners()</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

(#tab:simpletable)

<div data-custom-style="Table Caption">
<em>Engine type and number of gears</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Engine Type</th>
<th style="text-align: center;">3 gears</th>
<th style="text-align: center;">4 gears</th>
<th style="text-align: center;">5 gears</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">V-shaped</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Straight</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
<p>For more complex tables and example figures refer to the relevant section of the <a href="https://mfr.osf.io/render?url=https://osf.io/z6udg/?action=download%26mode=render">pdf</a> and <a href="https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render">R Markdown template</a> on the OSF page.</p>
</section>
<section id="using-citations" class="level1">
<h1>Using Citations</h1>
<p>The <code>citr</code> can be used to cite while you write much like using endnote with Word. I have exported my Zotero Library (using BetterBibTex) to a .bib “My Library.bib” file in the directory I am working in. To cite I simply use @ and the citation key e.g., <code>@haidt_emotional_2001</code> returns <span class="citation" data-cites="haidt_emotional_2001">Haidt (<a href="#ref-haidt_emotional_2001" role="doc-biblioref">2001</a>)</span>. To enclose the entire citation in parenthesis use square brackets <code>[@haidt_emotional_2001]</code> gives: <span class="citation" data-cites="haidt_emotional_2001">(<a href="#ref-haidt_emotional_2001" role="doc-biblioref">Haidt 2001</a>)</span>. The full reference is automatically added to the reference list (see below).</p>
<p>It is also generally good practice to cite R and the R packages you have used in your analyses. In the current post I used R <span class="citation" data-cites="R-base">(Version 4.1.2; <a href="#ref-R-base" role="doc-biblioref">R Core Team 2021</a>)</span> and the R-packages <em>blogdown</em> <span class="citation" data-cites="R-blogdown">(Version 1.16; <a href="#ref-R-blogdown" role="doc-biblioref">Xie, Hill, and Thomas 2017</a>)</span>, <em>bookdown</em> <span class="citation" data-cites="R-bookdown">(Version 0.32; <a href="#ref-R-bookdown" role="doc-biblioref">Xie 2016</a>)</span>, <em>citr</em> <span class="citation" data-cites="R-citr">(Version 0.3.2; <a href="#ref-R-citr" role="doc-biblioref">Aust 2019</a>)</span>, <em>desnum</em> <span class="citation" data-cites="R-desnum">(Version 0.1.1; <a href="#ref-R-desnum" role="doc-biblioref">McHugh 2017</a>)</span>, <em>extrafont</em> <span class="citation" data-cites="R-extrafont">(Version 0.19; <a href="#ref-R-extrafont" role="doc-biblioref">Winston Chang 2014</a>)</span>, <em>ggplot2</em> <span class="citation" data-cites="R-ggplot2">(Version 3.4.1; <a href="#ref-R-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span>, <em>knitr</em> <span class="citation" data-cites="R-knitr">(Version 1.42; <a href="#ref-R-knitr" role="doc-biblioref">Xie 2015</a>)</span>, <em>lsr</em> <span class="citation" data-cites="R-lsr">(Version 0.5.2; <a href="#ref-R-lsr" role="doc-biblioref">Navarro 2015</a>)</span>, <em>MASS</em> <span class="citation" data-cites="R-MASS">(Version 7.3.55; <a href="#ref-R-MASS" role="doc-biblioref"><strong>R-MASS?</strong></a>)</span>, <em>papaja</em> <span class="citation" data-cites="R-papaja">(Version 0.1.1.9001; <a href="#ref-R-papaja" role="doc-biblioref">Aust and Barth 2020</a>)</span>, <em>pwr</em> <span class="citation" data-cites="R-pwr">(Version 1.3.0; <a href="#ref-R-pwr" role="doc-biblioref">Champely 2020</a>)</span>, <em>scales</em> <span class="citation" data-cites="R-scales">(Version 1.2.1; <a href="#ref-R-scales" role="doc-biblioref">Wickham and Seidel 2020</a>)</span>, and <em>tinylabels</em> <span class="citation" data-cites="R-tinylabels">(Version 0.2.3; <a href="#ref-R-tinylabels" role="doc-biblioref"><strong>R-tinylabels?</strong></a>)</span>.</p>
<section id="references" class="level3">




</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aust_papaja_2017" class="csl-entry" role="listitem">
Aust, Frederik. 2017. <span>“Papaja (<span>Preparing APA Journal Articles</span>) Is an <span>R</span> Package That Provides Document Formats and Helper Functions to Produce Complete <span>APA</span> Manscripts from <span class="nocase">RMarkdown-files</span> (<span>PDF</span> and <span>Word</span> Documents).”</span>
</div>
<div id="ref-R-citr" class="csl-entry" role="listitem">
———. 2019. <em>Citr: ’<span>RStudio</span>’ Add-in to Insert Markdown Citations</em>. Manual.
</div>
<div id="ref-R-papaja" class="csl-entry" role="listitem">
Aust, Frederik, and Marius Barth. 2020. <em><span class="nocase">papaja</span>: <span>Create APA</span> Manuscripts with <span>R Markdown</span></em>. Manual.
</div>
<div id="ref-R-pwr" class="csl-entry" role="listitem">
Champely, Stephane. 2020. <em>Pwr: <span>Basic</span> Functions for Power Analysis</em>. Manual.
</div>
<div id="ref-haidt_emotional_2001" class="csl-entry" role="listitem">
Haidt, Jonathan. 2001. <span>“The Emotional Dog and Its Rational Tail: <span>A</span> Social Intuitionist Approach to Moral Judgment.”</span> <em>Psychological Review</em> 108 (4): 814–34. <a href="https://doi.org/10.1037/0033-295X.108.4.814">https://doi.org/10.1037/0033-295X.108.4.814</a>.
</div>
<div id="ref-R-desnum" class="csl-entry" role="listitem">
McHugh, Cillian. 2017. <em>Desnum: <span>Creates</span> Some Useful Functions</em>. Manual.
</div>
<div id="ref-R-lsr" class="csl-entry" role="listitem">
Navarro, Danielle. 2015. <em>Learning Statistics with <span>R</span>: <span>A</span> Tutorial for Psychology Students and Other Beginners. (<span>Version</span> 0.6)</em>. Manual. <span>Sydney, Australia</span>: <span>University of New South Wales</span>.
</div>
<div id="ref-R-base" class="csl-entry" role="listitem">
R Core Team. 2021. <em>R: <span>A</span> Language and Environment for Statistical Computing</em>. Manual. <span>Vienna, Austria</span>: <span>R Foundation for Statistical Computing</span>.
</div>
<div id="ref-R-ggplot2" class="csl-entry" role="listitem">
Wickham, Hadley. 2016. <em>Ggplot2: <span>Elegant</span> Graphics for Data Analysis</em>. <span>Springer-Verlag New York</span>.
</div>
<div id="ref-R-scales" class="csl-entry" role="listitem">
Wickham, Hadley, and Dana Seidel. 2020. <em>Scales: <span>Scale</span> Functions for Visualization</em>. Manual.
</div>
<div id="ref-R-extrafont" class="csl-entry" role="listitem">
Winston Chang. 2014. <em>Extrafont: <span>Tools</span> for Using Fonts</em>. Manual.
</div>
<div id="ref-R-knitr" class="csl-entry" role="listitem">
Xie, Yihui. 2015. <em>Dynamic <span>Documents</span> with <span>R</span> and Knitr</em>. Second. <span>Boca Raton, Florida</span>: <span>Chapman and Hall/CRC</span>.
</div>
<div id="ref-R-bookdown" class="csl-entry" role="listitem">
———. 2016. <em>Bookdown: <span>Authoring Books</span> and <span>Technical Documents</span> with <span>R Markdown</span></em>. <span>Boca Raton, Florida</span>: <span>Chapman and Hall/CRC</span>.
</div>
<div id="ref-R-blogdown" class="csl-entry" role="listitem">
Xie, Yihui, Alison Presmanes Hill, and Amber Thomas. 2017. <em>Blogdown: <span>Creating Websites</span> with <span>R Markdown</span></em>. <span>Boca Raton, Florida</span>: <span>Chapman and Hall/CRC</span>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The aim of this post is to help make these resources more accessible. As such, there will likely be a lot of duplication between this post and the resources on the OSF.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Italics are achieved by placing a star either side of the text you want italicised <code>*italics*</code> = <em>italics</em>; Bold is achieved by placing a double star either side of the text you want italicised <code>**bold**</code> = <strong>bold</strong><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>from the <code>desnum</code> package<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This test, and all tests that follow are for illustration purposes only, I have not checked any assumptions to see if I can run the tests, I just want to provide sample code that you can use for your own analyses.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><i class="fa-regular fa-copyright" aria-hidden="true"></i> Andreas Handel, 2022<br> All content licensed under <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-sa" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">(CC BY-NC-SA 4.0)</a></div>   
    <div class="nav-footer-center"><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-hidden="true"></i> and <a href="https://quarto.org/">Quarto</a><br> Inspiration and code snippets taken from <a href="../../posts/quarto-website-migration.html">these folks.</a><br> <a href="https://github.com/andreashandel/andreashandelwebsite">Source at <i class="fa-brands fa-github" aria-hidden="true"></i> GitHub</a></div>
  </div>
</footer>



</body></html>