---
title: "Music"
title-block-banner: "img/album_just_sky.jpg"
listing:
  contents: music
  sort: "date desc"
  type: default
  categories: true
  sort-ui: true
  filter-ui: true
page-layout: full
comments: false
css: styles_music.css
---


# Music

I have been playing music from a young age and started writing songs as a teenager. Influences range from heavy, multi-instrumental Prog (Yes, Rush, Pink Floyd and Genesis) to more traditional acoustic folk and blues (Neil Young, Eric Bibb and Tom Waits) and everything in between.

I have released 2 albums to date: [*Back to the Drawing Board*](https://www.cillianmchugh.com/music/back_to_the_drawing_board/) was released in 2012, and [*It Will Pass...*](https://www.cillianmchugh.com/music/it_will_pass/) was released in 2019. Both albums are available online (check out [Cillian Mc Hugh](https://open.spotify.com/artist/4YrhGzeBXwDn6FM4WfI8b1) on Spotify (also on [youtube music](https://music.youtube.com/channel/UCbR_uvTsZFNJvVznanBCOEA?feature=share), and [itunes](https://music.apple.com/ie/artist/cillian-mc-hugh/485620903)). Have a listen to the new album below. I also have the unreleased [*Spectrum*](https://www.cillianmchugh.com/music/spectrum/) which included some songs that made it onto *Back to the Drawing Board* along with some longer songs that reflect my Prog influences. Some material from [*Spectrum*](https://www.cillianmchugh.com/music/spectrum/) is available on [Soundcloud](https://soundcloud.com/cillianmchugh) (in particular see [this playlist](https://soundcloud.com/cillianmchugh/sets/long-songs)).

```{=html}
<br>



<div style="width:25%;height:25%;">
  <div style="position:relative;padding-top:56.25%;">
    <iframe src="https://www.youtube.com/embed/videoseries?list=OLAK5uy_mYaYyP7L_Zq72SMK54b7lnV3nFXMDiHmc" frameborder="0" allowfullscreen
      style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
  </div>
</div>


<br>


<br>
```

# More