{
  "hash": "92d3b967765158815a98534446f2c87a",
  "result": {
    "markdown": "---\ntitle: \"R Markdown Workshop\"\nauthor: \"CillianMacAodh (Cillian McHugh)\"\ndescription: Materials from a workshop on using RMarkdown\ndate: \"2019-08-03\"\naliases: \n  - ../rmarkdown-workshop\nbibliography      : [\"../../bib/My Library.bib\"]\nlink-citations: true\n\nreading_time: true  # Show estimated reading time?\nshare: true  # Show social sharing links?\nprofile: false  # Show author profile?\ncomments: false  # Show comments?\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n# Background\n\nThis is an unusual post for me, I have avoided writing about R Markdown because there are so many resources already available on the topic (e.g., [here](http://rmarkdown.rstudio.com/authoring_basics.html), [here](https://shiny.rstudio.com/articles/rmarkdown.html), and [here](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)).  However, recently I ran a session on using RMarkdown for my colleagues in the [Centre for Social Issues Research](http://www.ul.ie/csi-r/).  The aim of this was to demonstrate the usefulness of R Markdown (and hopefully convert a few people).  For this session I created a set of resources[^1] aimed at making the transition from SPSS to R Markdown a bit easier.  The *statistics* content of these resources is mainly just some of the simpler standard tests taught to psychology undergraduate students.\n\nThe complete resources are available on [this project page on the OSF](https://osf.io/nyu4g/).  The main purpose of the exercise was to provide people with the tools to create [this pdf](https://mfr.osf.io/render?url=https://osf.io/z6udg/?action=download%26mode=render) using [this R Markdown template](https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render). My hope is that by using this template, SPSS users might make the tranistion to R, and R Markdown (with the help of the wonderful [papaja](https://crsh.github.io/papaja_man/) package @aust_papaja_2017).\n\n[^1]: The aim of this post is to help make these resources more accessible.  As such, there will likely be a lot of duplication between this post and the resources on the OSF.\n\n\n\n# R Markdown Basics\n\nI started off the workshop by going through some of the basics of R Markdown.  When working with R Markdown, there are three types of text to be concerned with.\n\n1. **Plain text**: this is what you will use to write your manuscript.  The formatting of this plain text is fairly straight forward ([see this cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf))[^2]\n\n[^2]: Italics are achieved by placing a star either side of the text you want italicised `*italics*` = *italics*; Bold is achieved by placing a double star either side of the text you want italicised `**bold**` = **bold**\n\n2. **Code chunks**: these are denoted by three back ticks ` ``` `  at the top and the bottom of a chunk with commands in curly brackets in the title (on the same line as the firs set of back ticks). Code chunks allow you to run analyses without leaving your document. Output from code chunks can be included or omitted from your main output document.\n3. **In-line code**: this is denoted by a single back tick to begin a piece of code and a single back tick to close it `code goes here`.\n\nEach time you open a piece of code (a chunk or in-line code) you have to identify what language you want to code in. This is done by including the letter \"r\" in the curly brackets or immediately after the opening back tick.\n\n# Working with R\nIn order to show some of the basic functionality of R, I ran some analyses using the data sets that are built into R.  This means that anyone should be able to reproduce the analyses conducted using the [template](https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render) I provided (without needing to worry about loading data from other files).  I also provided another  [document](https://mfr.osf.io/render?url=https://osf.io/6vz4e/?action=download%26mode=render) with an accompanying [template](https://mfr.osf.io/render?url=https://osf.io/kub2w/?action=download%26mode=render) detailing the steps for inputting data into R. But this process is more prone to errors and if you are not familiar with R it can be a bit unintuitive. \n\n## Working with dataframes\n\nA dataframe is structured much like an SPSS file. There are rows and columns, the columns are named and generally represent variables. The rows (can also be named) generally represent cases. You can have multiple data frames loaded with different names, although they are commonly saved as `df` (and these can be numbered `df1 df2 df3`. If your document/code is well organised, it can be useful have a generic name for dataframes that you are working with. This means that much of your code can be recycled (particularly if the variable names are the same - if you run repeated studies, or studies with only minor changes, you will find that there is massive scope for recycling code - both chunks and in-line)\n\n### Some basics:\n\n1. The entire dataframe can be printed to the console by running the name of the data frame\n2. The dollar sign can be used to call specific variables from the data frame i.e., `df$variable_name`\n3. A function has the form \"function name\" followed by parenthesis: `function_name()`.\n4. The object that you want to run the function on goes in the parenthesis. e.g., if our dataframe was called `df`, and age was called `age` and we wanted to get the mean age we would run `mean(df$age)`.\n5. Sometimes missing data denoted by `NA` can mess with some functions, to account for this it is helpful to include the argument `na.rm = TRUE` in the function, e.g., `mean(df$age, na.rm = TRUE)`\n\nThe `mtcars` dataset comes with R.  For information on it simply type `help(mtcars)`.  The variables of interest here are `am` (transmission; 0 = automatic, 1 = manual), `mpg` (miles per gallon), `qsec` (1/4 mile time). Below we practice a few simple functions to find out information about the dataset. \n\n#### Example code and output:\n\n- Load the `mtcars` dataset into an object called `df` using the command `df <- mtcars`\n- View the variable names associated with `df` by running `variable.names(df)`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"mpg\"  \"cyl\"  \"disp\" \"hp\"   \"drat\" \"wt\"   \"qsec\" \"vs\"   \"am\"   \"gear\"\n[11] \"carb\"\n```\n:::\n:::\n\n\n- The mean miles per gallon can be calculated using `mean(df$mpg)`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20.09062\n```\n:::\n:::\n\n\n- The standard deviation of the same variable is calculated using `sd(df$mpg)`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.026948\n```\n:::\n:::\n\n\n- Or if you want to see basic descriptives use `descriptives(df$mpg)`[^3]\n\n[^3]: from the `desnum` package\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n      mean       sd  min  max len\n1 20.09062 6.026948 10.4 33.9  32\n```\n:::\n:::\n\n\n- To index by a variable we use square brackets `[]` and the `which()` function.\n  - The following command gets the mean miles per gallon for all cars with manual transmission: \n      - `mean(df$mpg[which(df$am==1)])`\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 24.39231\n```\n:::\n:::\n\n\n# Statistical tests\nNow that we know some of the basics, we'll try running some statistical tests.\n\n# Running a t-test\nI'm going to use the `mtcars` dataset to illustrate how to run and write up a t-test, in such a way that:\n\n(a) there is no copy/paste error in reporting values; and\n(b) you can recycle code and text.\n\nIn addition to `mpg` (miles per gallon), the other variable I am interested in is  `am` (transmission; 0 = automatic, 1 = manual).[^4]\n\n\n[^4]: This test, and all tests that follow are for illustration purposes only, I have not checked any assumptions to see if I can run the tests, I just want to provide sample code that you can use for your own analyses.\n\nThe question I'm going to look at is:\n\n(i) Is there a difference in miles per gallon depending on transmission?\n\n## T-test: Transmission and MPG\n\n- Load mtcars and save it in your environment using `df <- mtcars`\n- Create a new dataframe with a generic name e.g., `x` using the command: `x <- df`\n- This command runs the t-test and you can see the output in the console `t.test(x$mpg~x$am)`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  x$mpg by x$am\nt = -3.7671, df = 18.332, p-value = 0.001374\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -11.280194  -3.209684\nsample estimates:\nmean in group 0 mean in group 1 \n       17.14737        24.39231 \n```\n:::\n:::\n\n\n- The following code runs the t-test but saves the output as a list `t` that can be called later: `t <- t.test(x$mpg~x$am)`\n\n::: {.cell}\n\n:::\n\n\n- As with dataframes, specific variables within a list can be called using the dollar sign\n- To call the p value simply type `t$p.value`\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.001373638\n```\n:::\n:::\n\n- To call the t statistic, type `t$statistic`\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n        t \n-3.767123 \n```\n:::\n:::\n\n- And to call the degrees of freedom, type `t$parameter`\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n      df \n18.33225 \n```\n:::\n:::\n\n- Finally, to calculate the effect size and save it to an object type `td <- cohensD(mpg~am, data=x)`\n\n\n\n\n\nFrom the above we can call each value we need using in-line code to write up our results section as follows\n\n##### This is what the paragraph will look like in your Rmd document:\n\nAn independent samples t-test revealed a significant difference in miles per gallon between cars with automatic transmission\n(`*M*` = `` `r mean(x$mpg[which(x$am==0)])` ``, `*SD*` = `` `r sd(x$mpg[which(x$am==0)])` ``), and cars with manual transmission, (`*M*` = `` `r mean(x$mpg[which(x$am==1)])` ``, `*SD*` = `` `r sd(x$mpg[which(x$am==1)])` ``), `*t*`(`` `r t$parameter` ``) = `` `r t$statistic` ``, `*p*` `` `r paste(p_report(t$p.value))` ``, `*d*` = `` `r td ``.\n\n##### The above syntax will return the following:\n\nAn independent samples t-test revealed a significant difference in miles per gallon between cars with automatic transmission (*M* = 17.15, *SD* = 3.83), and cars with manual transmission, (*M* = 24.39, *SD* = 3.83), *t*(18.33) = -3.767, *p* = .001, *d* = 1.48.\n\nIf you want to run another t-test later on in your document you simply run it in a code chunk and create new objects (`t` and `td`) with the same names as before and you can use the same write up as above to report it. \n\n\n\n# Chi-square\n\nTo illustrate a chi-squared test I will test if there is an association between engine type `vs`  (0 = V-shaped, 1 = straight) and transmission type  (0 = automatic, 1 = manual). Again this is to illustrate the code/write up - not a real test.\n\n- First create a table using the command `table(x$am,x$vs)`\n- Running a chi-squared test using `chisq.test(table(x$am,x$vs))` returns:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(x$am, x$vs)\nX-squared = 0.34754, df = 1, p-value = 0.5555\n```\n:::\n:::\n\n\n- As with the t-test, in order to report it using in-line code you need to save the test as an object e.g., `c` using `c <- chisq.test(table(x$am,x$vs))`\n- Save the effect size using `w <- sqrt(c$statistic/(length(x$mpg)*c$parameter))`\n- And calculate the observed power using `pw <- pwr.chisq.test(w=w,N=length(x$mpg),df=(c$parameter),sig.level = .05)`\n\n##### Report using the following\n\nA chi-squared test for independence revealed no significant association between engine type and transmission type, `&chi;^2^`(`` `r c$parameter` ``, `*N*` = `` `r length(x$mpg)` ``) = `` `r c$statistic` ``, `*p*` `` `r paste(p_report(t$p.value))` ``, `*V*` = `` `r w ``, the observed power was `` `r pw$power` ``.\n\n\n##### The above returns the following:\n\nA chi-squared test for independence revealed no significant association between engine type and transmission type, &chi;^2^(1, *N* = 32) = 0.348, *p* = .556 *V* = 0.1, the observed power was 0.09. ([see this resource for effect size calculations for chi-squared tests](http://www.real-statistics.com/chi-square-and-f-distributions/effect-size-chi-square/)).\n\n\n# ANOVA and Correlation\n\nFor details on the ANOVA check out the [pdf](https://mfr.osf.io/render?url=https://osf.io/z6udg/?action=download%26mode=render) using the [R Markdown template](https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render) on the OSF page.  \n\n\n\n# Tables\nAgain using the `mtcars` dataset, I'm going to make a few tables. Bear in mind that the code for these tables is designed to be used along with the `papaja` package and rendered to pdf, so the html tables in this post will not be formatted as correctly as they should be (refer to the resources on the OSF to see what it should look like).\n\n- Firstly save `mtcars` as an object using `x <- mtcars`\n- We will make a table of engine type (V-shaped vs Straight) agains number of gears (3, 4, or 5) using `table(x$vs,x$gear)` which returns:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n   \n     3  4  5\n  0 12  2  4\n  1  3 10  1\n```\n:::\n:::\n\n\n- This table is useful to us, but it doesn't really sit well in our document\n- We can address this using the `apa_table()` function\n- Before using this function we need to create a matrix that can be passed through the function using the command `test <- as.data.frame.matrix(table(x$vs,x$gear))`\n- We can give names to the rows using `test <- `rownames<-`(test, c(\"V-shaped\",\"Straight\"))`\n- And we can give names to the columns using `test <- `colnames<-`(test, c(\"3 gears\",\"4 gears\",\"5 gears\"))`\n- Finally we pass our object (matrix) `test` through the `apa_table()` function to render a table that will be embedded in our document\n- The code below will generate the Table\\ \\@ref(tab:simpletable):\n\n\n\n```{.r .cell-code}\napa_table(\n   test\n   , align = c(\"l\", \"c\", \"c\", \"c\")\n   , caption = \"Engine type and number of gears\"\n   , added_stub_head = \"Engine Type\"\n   #, col_spanners = makespanners()\n   \n)\n```\n\n::: {.cell-output-display}\n<caption>(\\#tab:simpletable)</caption>\n\n<div custom-style='Table Caption'>*Engine type and number of gears*</div>\n\n\nEngine Type    3 gears    4 gears    5 gears \n------------  ---------  ---------  ---------\nV-shaped         12          2          4    \nStraight          3         10          1\n:::\n\n\nFor more complex tables and example figures refer to the relevant section of the [pdf](https://mfr.osf.io/render?url=https://osf.io/z6udg/?action=download%26mode=render) and [R Markdown template](https://mfr.osf.io/render?url=https://osf.io/5zsp8/?action=download%26mode=render) on the OSF page.\n\n\n# Using Citations\n\nThe `citr` can be used to cite while you write much like using endnote with Word. I have exported my Zotero Library (using BetterBibTex) to a .bib \"My Library.bib\" file in the directory I am working in. To cite I simply use @ and the citation key e.g., `@haidt_emotional_2001` returns @haidt_emotional_2001. To enclose the entire citation in parenthesis use square brackets `[@haidt_emotional_2001]` gives: [@haidt_emotional_2001]. The full reference is automatically added to the reference list (see below).\n\n\n\n\n\n\n\nIt is also generally good practice to cite R and the R packages you have used in your analyses. In the current post I used R [Version 4.1.2\\; @R-base] and the R-packages *blogdown* [Version 1.16\\; @R-blogdown], *bookdown* [Version 0.32\\; @R-bookdown], *citr* [Version 0.3.2\\; @R-citr], *desnum* [Version 0.1.1\\; @R-desnum], *extrafont* [Version 0.19\\; @R-extrafont], *ggplot2* [Version 3.4.1\\; @R-ggplot2], *knitr* [Version 1.42\\; @R-knitr], *lsr* [Version 0.5.2\\; @R-lsr], *MASS* [Version 7.3.55\\; @R-MASS], *papaja* [Version 0.1.1.9001\\; @R-papaja], *pwr* [Version 1.3.0\\; @R-pwr], *scales* [Version 1.2.1\\; @R-scales], and *tinylabels* [Version 0.2.3\\; @R-tinylabels].\n\n\n\n### References\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}