<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.287">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cillian McHugh">
<meta name="author" content="Run Zhang">
<meta name="author" content="Tanuja Karnatak">
<meta name="author" content="Nishtha Lamba">
<meta name="author" content="Olga Khokhlova">
<meta name="dcterms.date" content="2023-01-17">
<meta name="description" content="Cillian McHugh’s personal website.">

<title>Cillian McHugh - Just wrong? Or just WEIRD?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../..//files/icon1.png" rel="icon" type="image/png">
<script src="../../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-HN11FG1NGL"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-HN11FG1NGL', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  });
});
</script> 
  

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../customstyle.css">
<meta property="og:title" content="Cillian McHugh - Just wrong? Or just WEIRD?">
<meta property="og:description" content="Memory &amp; Cognition (2023)">
<meta property="og:image" content="https://www.cillianmchugh.com/publications/pubs/just-wrong-or-just-weird/index_files/figure-html/chinesefig-1.png">
<meta property="og:site-name" content="Cillian McHugh">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="Cillian McHugh - Just wrong? Or just WEIRD?">
<meta name="twitter:description" content="Memory &amp; Cognition (2023)">
<meta name="twitter:image" content="https://www.cillianmchugh.com/publications/pubs/just-wrong-or-just-weird/featured.png">
<meta name="twitter:creator" content="@CillianMacAodh">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Cillian McHugh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../posts.html" rel="" target="">
 <span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../publications.html" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../music.html" rel="" target="">
 <span class="menu-text">Music</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../other.html" rel="" target="">
 <span class="menu-text">Other</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../rblog.html" rel="" target="">
 <span class="menu-text">R Blog</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#evidence-for-moral-dumbfounding" id="toc-evidence-for-moral-dumbfounding" class="nav-link active" data-scroll-target="#evidence-for-moral-dumbfounding">Evidence for Moral Dumbfounding</a></li>
  <li><a href="#competing-interpretations-of-the-dumbfounding-narrative" id="toc-competing-interpretations-of-the-dumbfounding-narrative" class="nav-link" data-scroll-target="#competing-interpretations-of-the-dumbfounding-narrative">Competing Interpretations of the Dumbfounding Narrative</a></li>
  <li><a href="#moral-dumbfounding-and-moral-universals" id="toc-moral-dumbfounding-and-moral-universals" class="nav-link" data-scroll-target="#moral-dumbfounding-and-moral-universals">Moral Dumbfounding and Moral Universals</a></li>
  <li><a href="#individualcultural-differences" id="toc-individualcultural-differences" class="nav-link" data-scroll-target="#individualcultural-differences">Individual/Cultural Differences</a></li>
  <li><a href="#the-current-research" id="toc-the-current-research" class="nav-link" data-scroll-target="#the-current-research">The Current Research</a></li>
  <li><a href="#study-1---chinese-sample" id="toc-study-1---chinese-sample" class="nav-link" data-scroll-target="#study-1---chinese-sample">Study 1 - Chinese Sample</a>
  <ul class="collapse">
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#participants-and-design" id="toc-participants-and-design" class="nav-link" data-scroll-target="#participants-and-design">Participants and design</a></li>
  <li><a href="#procedure-and-materials" id="toc-procedure-and-materials" class="nav-link" data-scroll-target="#procedure-and-materials">Procedure and materials</a></li>
  </ul></li>
  <li><a href="#results-and-discussion" id="toc-results-and-discussion" class="nav-link" data-scroll-target="#results-and-discussion">Results and Discussion</a>
  <ul class="collapse">
  <li><a href="#judgements-of-the-scenarios" id="toc-judgements-of-the-scenarios" class="nav-link" data-scroll-target="#judgements-of-the-scenarios">Judgements of the scenarios</a></li>
  <li><a href="#tables-of-other-responses" id="toc-tables-of-other-responses" class="nav-link" data-scroll-target="#tables-of-other-responses">Tables of other Responses</a></li>
  <li><a href="#measuring-dumbfounding" id="toc-measuring-dumbfounding" class="nav-link" data-scroll-target="#measuring-dumbfounding">Measuring dumbfounding</a></li>
  <li><a href="#individual-differences-study-1a" id="toc-individual-differences-study-1a" class="nav-link" data-scroll-target="#individual-differences-study-1a">Individual differences (Study 1a)</a></li>
  <li><a href="#individual-differences-study-1b" id="toc-individual-differences-study-1b" class="nav-link" data-scroll-target="#individual-differences-study-1b">Individual differences (Study 1b)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#study-2---indian-sample" id="toc-study-2---indian-sample" class="nav-link" data-scroll-target="#study-2---indian-sample">Study 2 - Indian Sample</a>
  <ul class="collapse">
  <li><a href="#method-1" id="toc-method-1" class="nav-link" data-scroll-target="#method-1">Method</a>
  <ul class="collapse">
  <li><a href="#participants-and-design-1" id="toc-participants-and-design-1" class="nav-link" data-scroll-target="#participants-and-design-1">Participants and design</a></li>
  <li><a href="#procedure-and-materials-1" id="toc-procedure-and-materials-1" class="nav-link" data-scroll-target="#procedure-and-materials-1">Procedure and materials</a></li>
  </ul></li>
  <li><a href="#results-and-discussion-1" id="toc-results-and-discussion-1" class="nav-link" data-scroll-target="#results-and-discussion-1">Results and Discussion</a>
  <ul class="collapse">
  <li><a href="#judgements-of-the-scenarios-1" id="toc-judgements-of-the-scenarios-1" class="nav-link" data-scroll-target="#judgements-of-the-scenarios-1">Judgements of the scenarios</a></li>
  <li><a href="#measuring-dumbfounding-1" id="toc-measuring-dumbfounding-1" class="nav-link" data-scroll-target="#measuring-dumbfounding-1">Measuring dumbfounding</a></li>
  <li><a href="#individual-differences" id="toc-individual-differences" class="nav-link" data-scroll-target="#individual-differences">Individual differences</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#study-3---mixed-sample" id="toc-study-3---mixed-sample" class="nav-link" data-scroll-target="#study-3---mixed-sample">Study 3 - Mixed Sample</a>
  <ul class="collapse">
  <li><a href="#method-2" id="toc-method-2" class="nav-link" data-scroll-target="#method-2">Method</a>
  <ul class="collapse">
  <li><a href="#participants-and-design-2" id="toc-participants-and-design-2" class="nav-link" data-scroll-target="#participants-and-design-2">Participants and design</a></li>
  <li><a href="#procedure-and-materials-2" id="toc-procedure-and-materials-2" class="nav-link" data-scroll-target="#procedure-and-materials-2">Procedure and materials</a></li>
  </ul></li>
  <li><a href="#results-and-discussion-2" id="toc-results-and-discussion-2" class="nav-link" data-scroll-target="#results-and-discussion-2">Results and Discussion</a>
  <ul class="collapse">
  <li><a href="#judgements-of-the-scenarios-2" id="toc-judgements-of-the-scenarios-2" class="nav-link" data-scroll-target="#judgements-of-the-scenarios-2">Judgements of the scenarios</a></li>
  <li><a href="#measuring-dumbfounding-2" id="toc-measuring-dumbfounding-2" class="nav-link" data-scroll-target="#measuring-dumbfounding-2">Measuring dumbfounding</a></li>
  <li><a href="#individual-differences-1" id="toc-individual-differences-1" class="nav-link" data-scroll-target="#individual-differences-1">Individual differences</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#general-discussion" id="toc-general-discussion" class="nav-link" data-scroll-target="#general-discussion">General Discussion</a>
  <ul class="collapse">
  <li><a href="#individual-differences-and-dumbfounded-responding" id="toc-individual-differences-and-dumbfounded-responding" class="nav-link" data-scroll-target="#individual-differences-and-dumbfounded-responding">Individual Differences and Dumbfounded Responding</a></li>
  <li><a href="#limitations-and-future-directions" id="toc-limitations-and-future-directions" class="nav-link" data-scroll-target="#limitations-and-future-directions">Limitations and Future directions</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#data-accessibility-statement" id="toc-data-accessibility-statement" class="nav-link" data-scroll-target="#data-accessibility-statement">Data Accessibility Statement</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Just wrong? Or just WEIRD?</h1>
<p class="subtitle lead">Investigating the prevalence of moral dumbfounding in non-Western samples</p>
  <div class="quarto-categories">
    <div class="quarto-category">morality</div>
    <div class="quarto-category">moral dumbfounding</div>
    <div class="quarto-category">WEIRD</div>
  </div>
  </div>

<div>
  <div class="description">
    Memory &amp; Cognition (2023)
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Cillian McHugh </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Limerick
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Run Zhang </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Limerick
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Tanuja Karnatak </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Limerick
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Nishtha Lamba </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Middlesex University Dubai
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Olga Khokhlova </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Middlesex University Dubai
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>Moral dumbfounding occurs when people maintain a moral judgment even though they cannot provide a reason for this judgment. Dumbfounded responding may include admitting to not having reasons, or the use of unsupported declarations (“It’s just wrong”) as justification for a judgment. Published evidence for dumbfounding has drawn exclusively on samples of WEIRD backgrounds (Western, educated, industrialized, rich, and democratic), and it remains unclear to what extent the phenomenon is generalizable to other populations. Furthermore, the theoretical implications of moral dumbfounding have been disputed in recent years. In three studies we apply a standardized moral dumbfounding task, and show evidence for moral dumbfounding in a Chinese sample (Study 1, N = 165), an Indian sample (Study 2, N = 181), and a mixed sample primarily (but not exclusively) from North Africa and the Middle East (MENA region, Study 3, N = 264). These findings are consistent with a categorization theories of moral judgment.”</p>
</blockquote>
<button type="button" class="btn btn-primary btn-sm" onclick="window.open('https://raw.githubusercontent.com/cillianmiltown/website_quarto/main/publications/pubs/just-wrong-or-just-weird/WEIRD.pdf');" data-inline="true">
PDF
</button>
<button type="button" class="btn btn-primary btn-sm" onclick="window.open('https://link.springer.com/article/10.3758/s13421-022-01386-z');" data-inline="true">
Source Document
</button>
<button type="button" class="btn btn-primary btn-sm" onclick="window.open('https://osf.io/2h3k7/');" data-inline="true">
OSF
</button>
<p><br></p>


<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>
Bibliography
</title>


<div class="csl-bib-body" style="line-height: 2; margin-left: 2em; text-indent:-2em;" role="list">
<div class="csl-entry" role="listitem">
McHugh, C., Zhang, R., Karnatak, T., Lamba, N., &amp; Khokhlova, O. (2023). Just wrong? Or just WEIRD? Investigating the prevalence of moral dumbfounding in non-Western samples. <i>Memory &amp; Cognition</i>. <a href="https://doi.org/10.3758/s13421-022-01386-z">https://doi.org/10.3758/s13421-022-01386-z</a>
</div>
<p><span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10.3758%2Fs13421-022-01386-z&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Just%20wrong%3F%20Or%20just%20WEIRD%3F%20Investigating%20the%20prevalence%20of%20moral%20dumbfounding%20in%20non-Western%20samples&amp;rft.jtitle=Memory%20%26%20Cognition&amp;rft.stitle=Mem%20Cogn&amp;rft.aufirst=Cillian&amp;rft.aulast=McHugh&amp;rft.au=Cillian%20McHugh&amp;rft.au=Run%20Zhang&amp;rft.au=Tanuja%20Karnatak&amp;rft.au=Nishtha%20Lamba&amp;rft.au=Olga%20Khokhlova&amp;rft.date=2023-01-17&amp;rft.issn=1532-5946&amp;rft.language=en"></span></p>
</div>


<p>The phenomenon of moral dumbfounding occurs when people defend a moral judgement even though they cannot provide a reason in support of this judgement <span class="citation" data-cites="haidt_moral_2000 mchugh_searching_2017a">(<a href="#ref-haidt_moral_2000" role="doc-biblioref">Haidt, Björklund, and Murphy 2000</a>; <a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>)</span>. It typically manifests as an explicit admission of not having reasons, or the use of unsupported declarations (e.g., “It’s just wrong”) as a justification for a judgement. For almost two decades, evidence for moral dumbfounding was limited to a single study, unpublished in peer reviewed form, and with a total sample of <em>N</em> = 30 <span class="citation" data-cites="haidt_moral_2000">(<a href="#ref-haidt_moral_2000" role="doc-biblioref">Haidt, Björklund, and Murphy 2000</a>)</span>. This meant that, while the phenomenon was widely discussed in the literature, its existence was not well supported by empirical evidence. Recent work <span class="citation" data-cites="mchugh_searching_2017a mchugh_reasons_2020">(<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>, <a href="#ref-mchugh_reasons_2020" role="doc-biblioref">2020</a>)</span>, has provided additional evidence for the existence moral dumbfounding, demonstrating that it can be reliably elicited <span class="citation" data-cites="royzman_curious_2015 mchugh_reasons_2020">(though perhaps it not as widespread as previously assumed, see <a href="#ref-royzman_curious_2015" role="doc-biblioref">Royzman, Kim, and Leeman 2015</a>; <a href="#ref-mchugh_reasons_2020" role="doc-biblioref">McHugh et al. 2020</a>)</span>.</p>
<p>Despite this recent work, it remains unclear how universal or generalisable the phenomenon is. Current evidence is limited to research involving exclusively WEIRD <span class="citation" data-cites="henrich_most_2010">(Western, educated, industrialised, rich, and democratic, see <a href="#ref-henrich_most_2010" role="doc-biblioref">Henrich, Heine, and Norenzayan 2010</a>)</span> samples. The purpose of the current research is to extend research on moral dumbfounding beyond these exclusively WEIRD contexts. Specifically we test for the presence of moral dumbfounding in a Chinese sample (Study 1), in an Indian sample (Study 2), and in a mixed sample from a diverse range of non-WEIRD countries (Study 3).</p>
<section id="evidence-for-moral-dumbfounding" class="level1">
<h1>Evidence for Moral Dumbfounding</h1>
<p>The earliest documented evidence for dumbfounded responding on moral issues comes from a study by <span class="citation" data-cites="haidt_affect_1993">Haidt, Koller, and Dias (<a href="#ref-haidt_affect_1993" role="doc-biblioref">1993</a>)</span>. In this study participants were asked to judge a range of moral scenarios. In addition, participants were asked and to justify their judgements. Some scenarios were potentially offensive but ostensibly harmless (e.g., a family eating their family dog after it was killed by a car; cutting up and using the national flag to clean a bathroom). <span class="citation" data-cites="haidt_affect_1993">Haidt, Koller, and Dias (<a href="#ref-haidt_affect_1993" role="doc-biblioref">1993</a>)</span> found that some participants struggled to provide justifications for their judgements, and in some cases, resorted to providing unsupported declarations as justification, e.g., “Because it’s wrong to eat your dog” <span class="citation" data-cites="haidt_affect_1993">(<a href="#ref-haidt_affect_1993" role="doc-biblioref">Haidt, Koller, and Dias 1993, 632</a>)</span>.</p>
<p>In a later study this type of responding was investigated specifically, and the term <em>moral dumbfounding</em> was coined <span class="citation" data-cites="haidt_moral_2000">(<a href="#ref-haidt_moral_2000" role="doc-biblioref">Haidt, Björklund, and Murphy 2000</a>)</span>. In a series of interviews, <span class="citation" data-cites="haidt_moral_2000">Haidt, Björklund, and Murphy (<a href="#ref-haidt_moral_2000" role="doc-biblioref">2000</a>)</span> presented participants with moral scenarios depicting taboo behaviours that did not result in any harm.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> These scenarios (referred to as <em>intuition</em> scenarios) were designed to appear intuitively “wrong” but the absence of any resultant harm meant that providing a reason for judging the behaviour as wrong was difficult for participants. Responses to these <em>intuition</em> scenarios were contrasted against responses to a traditional <em>reasoning</em> scenario - the classic <em>Heinz</em> dilemma.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Participants were able justify their judgements of the <em>reasoning</em> scenario, however, for the the <em>intuition</em> scenarios participants struggled to provide reasons for their judgements, presenting as morally dumbfounded.</p>
<p>While <span class="citation" data-cites="haidt_moral_2000">Haidt, Björklund, and Murphy (<a href="#ref-haidt_moral_2000" role="doc-biblioref">2000</a>)</span> appeared to provide evidence for moral dumbfounding, this study did not provide standardised methods for systematically eliciting moral dumbfounding. More crucially, this work did not identify a formal measure of dumbfounded responding. Later work by <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span> addressed both of these limitations. Replicating and extending the original work by <span class="citation" data-cites="haidt_moral_2000">Haidt, Björklund, and Murphy (<a href="#ref-haidt_moral_2000" role="doc-biblioref">2000</a>)</span>, <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span> identified two measurable responses that were indicative of moral dumbfounding (admissions of not having reasons, and the use of unsupported declarations as justification for a judgement). Furthermore, <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span> developed a computer-based task that reliably elicited these responses, thus providing both additional evidence for moral dumbfounding, and the means to study it more systematically, and on a larger scale.</p>
</section>
<section id="competing-interpretations-of-the-dumbfounding-narrative" class="level1">
<h1>Competing Interpretations of the Dumbfounding Narrative</h1>
<p>The dominant narrative surrounding moral dumbfounding presents it as evidence for the intuitive nature of moral judgements, over more rationalist perspectives <span class="citation" data-cites="haidt_emotional_2001">(see <a href="#ref-haidt_emotional_2001" role="doc-biblioref">Haidt 2001</a>)</span>. According to this view, moral judgements are based on intuitions rather than on principles or reasons. Recent theorists <span class="citation" data-cites="royzman_curious_2015">(e.g., <a href="#ref-royzman_curious_2015" role="doc-biblioref">Royzman, Kim, and Leeman 2015</a>)</span> have challenged this, arguing that moral judgements, even in the dumbfounding paradigm, are based on reasons or principles. Some of these challenges are theoretical <span class="citation" data-cites="sneddon_social_2007 wielenberg_robust_2014 dwyer_moral_2009 jacobson_moral_2012 guglielmo_unfounded_2018">(e.g., <a href="#ref-sneddon_social_2007" role="doc-biblioref">Sneddon 2007</a>; <a href="#ref-wielenberg_robust_2014" role="doc-biblioref">Wielenberg 2014</a>; <a href="#ref-dwyer_moral_2009" role="doc-biblioref">Dwyer 2009</a>; <a href="#ref-jacobson_moral_2012" role="doc-biblioref">Jacobson 2012</a>; <a href="#ref-guglielmo_unfounded_2018" role="doc-biblioref">Guglielmo 2018</a>)</span>, while others include empirical work testing assumptions relevant to dumbfounding <span class="citation" data-cites="gray_myth_2014 gray_impure_2015">(e.g., <a href="#ref-gray_myth_2014" role="doc-biblioref">Gray, Schein, and Ward 2014</a>; <a href="#ref-gray_impure_2015" role="doc-biblioref">Gray and Keeney 2015</a>)</span>, or testing the dumbfounding paradigm directly <span class="citation" data-cites="stanley_reasonbased_2019a royzman_curious_2015">(e.g., <a href="#ref-stanley_reasonbased_2019a" role="doc-biblioref"><strong>stanley_reasonbased_2019a?</strong></a>; <a href="#ref-royzman_curious_2015" role="doc-biblioref">Royzman, Kim, and Leeman 2015</a>)</span>. A common theme permeating these challenges is that moral dumbfounding is not a <em>real</em> phenomenon, and that the responding observed emerges as a consequence of the experimental paradigm.</p>
<p>The strongest challenges to the dumbfounding narrative, appear to empirically demonstrate that people’s judgements in the dumbfounding paradigm may be attributed to specific reasons, e.g., either harm-based (believing an action may cause harm) reasons or norm-based (breaking a moral norm is inherently wrong) reasons <span class="citation" data-cites="royzman_curious_2015 stanley_reasonbased_2019a">(see, <a href="#ref-royzman_curious_2015" role="doc-biblioref">Royzman, Kim, and Leeman 2015</a>; <a href="#ref-stanley_reasonbased_2019a" role="doc-biblioref"><strong>stanley_reasonbased_2019a?</strong></a>)</span>. However, addressing key methodological limitations in <span class="citation" data-cites="royzman_curious_2015">Royzman, Kim, and Leeman (<a href="#ref-royzman_curious_2015" role="doc-biblioref">2015</a>)</span>, <span class="citation" data-cites="mchugh_reasons_2020">McHugh et al. (<a href="#ref-mchugh_reasons_2020" role="doc-biblioref">2020</a>)</span> demonstrated critical inconsistencies in people’s responding that undermine these reason based explanations<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> providing additional evidence that moral dumbfounding is indeed a real phenomenon, though perhaps it is not as widespread as earlier reports suggest.</p>
</section>
<section id="moral-dumbfounding-and-moral-universals" class="level1">
<h1>Moral Dumbfounding and Moral Universals</h1>
<p>It is well established that moral judgement, moral development, and moral values can vary across cultures and across countries <span class="citation" data-cites="haidt_affect_1993 vasquez_cultural_2001 vasudev_moral_1987">(<a href="#ref-haidt_affect_1993" role="doc-biblioref">Haidt, Koller, and Dias 1993</a>; <a href="#ref-vasquez_cultural_2001" role="doc-biblioref">Vasquez et al. 2001</a>; <a href="#ref-vasudev_moral_1987" role="doc-biblioref">Vasudev and Hummel 1987</a>)</span>. There have been some attempts to develop taxonomies of moral values or systems <span class="citation" data-cites="haidt_moral_2008 shweder_big_1997">(e.g., <a href="#ref-haidt_moral_2008" role="doc-biblioref">Haidt and Joseph 2008</a>; <a href="#ref-shweder_big_1997" role="doc-biblioref">Shweder et al. 1997</a>)</span> that can be applied cross culturally or across different countries. However, the evidence for the universality of these approaches is inconsistent, leading some theorists to conclude that there are no moral universals <span class="citation" data-cites="davis_moral_2015 doris_how_2008 machery_evolution_2010 prinz_morality_2008 prinz_resisting_2008">(e.g., <a href="#ref-davis_moral_2015" role="doc-biblioref">Davis et al. 2015</a>; <a href="#ref-doris_how_2008" role="doc-biblioref">Doris and Plakias 2008</a>; <a href="#ref-machery_evolution_2010" role="doc-biblioref">Machery and Mallon 2010</a>; <a href="#ref-prinz_morality_2008" role="doc-biblioref">Prinz 2008a</a>, <a href="#ref-prinz_resisting_2008" role="doc-biblioref">2008b</a>)</span>.</p>
<p>At present the evidence for moral dumbfounding is based exclusively on studies involving participants from WEIRD <span class="citation" data-cites="henrich_most_2010">(<a href="#ref-henrich_most_2010" role="doc-biblioref">Henrich, Heine, and Norenzayan 2010</a>)</span> samples. The failure to study moral dumbfounding beyond WEIRD contexts presents a key limitation of our understanding of the phenomenon, such that it is not clear whether the phenomenon exists in other contexts. Despite the limited generalizability of moral dumbfounding, the existence of the phenomenon has informed inferences about the nature of the cognitive processes that underlie moral judgement <span class="citation" data-cites="haidt_emotional_2001">(e.g., <a href="#ref-haidt_emotional_2001" role="doc-biblioref">Haidt 2001</a>)</span>. The generalizability these inferences would be undermined significantly if moral dumbfounding is unique to specific samples. The current studies aim to address this limitation and extend the study of moral dumbfounding beyond studies of exclusively WEIRD participants.</p>
</section>
<section id="individualcultural-differences" class="level1">
<h1>Individual/Cultural Differences</h1>
<p>Given that this is the first study of moral dumbfounding in a non-WEIRD setting, we additionally investigated the potential influence of culturally relevant individual differences on moral dumbfounding. A measure that is widely regarded as one of the most prominent dimensions that varies with culture is individualism/collectivism <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>, and as such we included this in our study for exploratory purposes.</p>
<p>In order to assess the possible influence of individualism/collectivism, we included the individualism-collectivism scale <span class="citation" data-cites="triandis_individualism_2011 li_dimensionality_2007 renzhi_key_2013">(ICS: <a href="#ref-triandis_individualism_2011" role="doc-biblioref">Triandis and Gelfand 2011</a>; <a href="#ref-li_dimensionality_2007" role="doc-biblioref">Li and Aksoy 2007</a>; <a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>. This scale includes four dimensions: collectivism, individualism, horizontal, vertical. Collectivism is characterized by common goals, interpersonal relationships, social dependencies and connections. Collectivists regard themselves as members of an organization, and they believe that their actions should conform to the collective beliefs and obligations. Individualism emphasizes individual goals and independence. Individualists regard themselves as being separated from within an organization. Individualist behaviour depends on expectations and estimates of effectiveness. Horizontal refers to egalitarianism, while vertical emphasizes authority, principles, and hierarchy <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>.</p>
<p>Regarding the specific combinations of these dimensions, vertical collectivism (VC) maintains the authoritative structure within the organization, supporting self-sacrifice and competition outside the organization. In addition to treating the self as part of the organization, horizontal collectivism (HC) also emphasizes the equality of members within the group. Vertical individualism (VI) means the increase of achievement based on individualism, with emphasis on independence and placing the self on any interpersonal relationship. Horizontal individualism (HI) refers to the addition of universal values based on individualism, and independence is to maintain a certain meaning or freedom within a principle <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>.</p>
</section>
<section id="the-current-research" class="level1">
<h1>The Current Research</h1>
<p>In response to the WEIRD-centric nature of research on moral dumbfounding, we present two studies, extending research on moral dumbfounding to non-WEIRD samples. In Study 1 we assess whether or not moral dumbfounding can be elicited in a Chinese sample. In Study 2 we investigate whether or not moral dumbfounding can be found in an Indian sample. In Study 3 we test for moral dumbfounding in a sample from a diverse range of countries.</p>
</section>
<section id="study-1---chinese-sample" class="level1">
<h1>Study 1 - Chinese Sample</h1>
<p>In Study 1 we adapted the methods and materials developed by <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span> for use in a Chinese context. The primary aim of Study 1 was to investigate if moral dumbfounding can be elicited in a Chinese sample. Furthermore, we measure individual differences in individualism / collectivism and test for a possible relationship between these dimensions and dumbfounded responding.</p>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<section id="participants-and-design" class="level3">
<h3 class="anchored" data-anchor-id="participants-and-design">Participants and design</h3>
<p>Study 1 was a frequency based attempted replication of <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span>. The aim of Study 1 was to identify if dumbfounded responding could be evoked in a Chinese context. Results are primarily descriptive. We have included exploratory analyses investigating the possible influence of individualism/collectivism <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> on responding.</p>
<p>An initial sample of 42 (34 female, 8 male, 0 other; <em>M<sub>age</sub></em> = 21.43, min = 18, max = 27, <em>SD</em> = 1.74) participants took part. An additional 123 (75 female, 48 male, 0 other; <em>M</em><sub>age</sub> = 22.06, min = 18, max = 45, <em>SD</em> = 3.76) participants completed a follow-up study with the <em>Cannibal</em> scenario only, and in which we experimentally manipulated psychological distance <span class="citation" data-cites="liberman_psychological_2007">(drawing on construal level theory e.g., <a href="#ref-liberman_psychological_2007" role="doc-biblioref">Liberman, Trope, and Stephan 2007</a>)</span>. The experimental manipulation had no influence on dumbfounded responding, <span class="math inline">\(\chi\)</span><sup>2</sup>(2, <em>N</em> = 123) = 2.304, <em>p</em> = .316, <em>V</em> = 0.1023383, and as such we have included these participants in the current analysis (for clarity these studies are reported separately as Study 1a and Study 1b). Participants in this study were undergraduate students and postgraduate students, from Luoyang Normal University (China). All participants were recruited from China and had a high level of Chinese, the entire online questionnaire survey was presented in Chinese. Participation was voluntary and participants were not reimbursed for their participation.</p>
</section>
<section id="procedure-and-materials" class="level3">
<h3 class="anchored" data-anchor-id="procedure-and-materials">Procedure and materials</h3>
<p>Data were collected through the Chinese language online survey software Wenjuanxing <span class="citation" data-cites="_wenjuanxing_2006">(<a href="#ref-_wenjuanxing_2006" role="doc-biblioref"><span>“Wenjuanxing”</span> 2006</a>)</span>. Participants were provided with a link to the online survey. The first page of the survey was an information sheet. If participants chose to continue, they proceeded to the second page, the consent form. Participants could only proceed to the remainder of the survey if they provide consent on the consent form. Upon providing consent and proceeding, participants completed some questions relating to basic demographics.</p>
<p>The procedure and materials for the moral dumbfounding task were taken directly from <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span>. These were translated into Chinese by a member of the research team whose native language was Chinese. Four moral judgement scenarios were used, two “intuition” scenarios: <em>Incest</em>, <em>Cannibal</em>, and two “reasoning” scenarios <em>Trolley</em>, <em>Heinz</em> <span class="citation" data-cites="mchugh_searching_2017a">(taken from <a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>, see Appendix A)</span>.</p>
<p><strong><em>Moral dumbfounding task.</em></strong> The basic procedure for moral dumbfounding tasks is as follows. Participants are presented with a scenario to read. They are then asked to rate, on a 7-point Likert scale (1 = <em>Morally wrong</em>; 4 = <em>Neutral</em>; 7 = <em>Morally right</em>), how right or wrong they regarded the behaviour described in the scenario. Following this participants are asked to rate their confidence in their judgement (again on a 7-point Likert scale). Participants are then presented with a series of counterarguments, which refuted commonly used justifications for rating the behaviours as “wrong” (see Appendix B). After each counter-argument, participants are asked “Do you (still) think it is wrong?”, with a binary “yes/no” response option; and then they are asked “Do you have a reason for your judgement?”, with three possible response option “Yes, I have a reason”, “No I have no reason”, and “Unsure”. This sequence was repeated for each of the three counter-arguments.</p>
<p>Dumbfounding is measured using the “critical slide” which contains a statement defending the behaviour, and a question asking how the behaviour could be wrong (see Appendix C). There are three possible answer options: (a) “There is nothing wrong”; (b) an admission of not having reasons (“It’s wrong but I can’t think of a reason”); and finally a judgement with accompanying justification (c) “It’s wrong and I can provide a valid reason”. The selecting of option (b), the admission of not having reasons, is taken to be a dumbfounded response. Participants who selected (c) were promoted to type a reason on the next page. The order of these response options was randomised.</p>
<p>Following the critical slide, participants rated the behaviour again, and completed the post-discussion questionnaire devised by <span class="citation" data-cites="haidt_moral_2000">Haidt, Björklund, and Murphy (<a href="#ref-haidt_moral_2000" role="doc-biblioref">2000</a>)</span>. They were required to rate on a 7-point Likert scale how sure were they about their judgement; how much they changed their mind; how confused were they; how irritated were they; how much was their judgement based on reason; how much was their judgement based on “gut” feeling (see Appendix D). This process is repeated in full for each moral scenario. The order of presentation of the moral scenarios was randomised.</p>
<p><strong><em>Coding reasons.</em></strong> While there is a strong theoretical and empirical case for coding the reasons provided for unsupported declarations or tautological responses, as dumbfounded responses <span class="citation" data-cites="mchugh_searching_2017a">(see <a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>)</span>, this approach has been challenged by claims that these responses constitute the expression of a normative position <span class="citation" data-cites="royzman_curious_2015">(e.g., <a href="#ref-royzman_curious_2015" role="doc-biblioref">Royzman, Kim, and Leeman 2015</a>)</span>. In response to this challenge, we adopt an “admission of not having reasons” as the only measure of moral dumbfounding in these studies. While this measure provides a more conservative estimate of the prevalence of moral dumbfounding, it provides a considerably less ambiguous estimate.</p>
<p><strong><em>Individualism-collectivism scale.</em></strong> Following the dumbfounding task, participants completed the individualism-collectivism scale <span class="citation" data-cites="li_dimensionality_2007">(<a href="#ref-li_dimensionality_2007" role="doc-biblioref">Li and Aksoy 2007</a>, see Appendix E)</span>. This sixteen-item scale includes four sub-scales: Vertical Collectivism (VC), Horizontal Collectivism (HC), Vertical Individualism (VI) and Horizontal Individualism (HI). The responses were recorded on a 9-point Likert scale ranging from 1 = <em>strongly disagree</em>, to 9 = <em>strongly agree</em>. The entire study lasted approximately twenty minutes.</p>
</section>
</section>
<section id="results-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="results-and-discussion">Results and Discussion</h2>
<section id="judgements-of-the-scenarios" class="level3">
<h3 class="anchored" data-anchor-id="judgements-of-the-scenarios">Judgements of the scenarios</h3>
<p>The mean initial ratings for each scenario are as follows: <em>M<sub>Heinz</sub></em> = 4.76, <em>SD<sub>Heinz</sub></em> = 2.07; <em>M<sub>Cannibal</sub></em> = 1.52, <em>SD<sub>Cannibal</sub></em> = 1.13; <em>M<sub>Incest</sub></em> = 2.88, <em>SD<sub>Incest</sub></em> = 2.23; <em>M<sub>Trolley</sub></em> = 3.29, <em>SD<sub>Trolley</sub></em> = 1.95. The mean revised ratings for each scenario are as follows: <em>M<sub>Heinz</sub></em> = 4.74, <em>SD<sub>Heinz</sub></em> = 2.04; <em>M<sub>Cannibal</sub></em> = 1.6, <em>SD<sub>Cannibal</sub></em> = 1.08; <em>M<sub>Incest</sub></em> = 2.9, <em>SD<sub>Incest</sub></em> = 2.13; <em>M<sub>Trolley</sub></em> = 3.36, <em>SD<sub>Trolley</sub></em> = 2.03. The proportion of wrong, neutral, and ok, judgements for each scenario are displayed in Table&nbsp;@ref(tab:tab2judge).</p>
<div class="cell-output-display">

(#tab:tab2judge)

<div data-custom-style="Table Caption">
<em>Valence of initial and revised judgements for each scenarion for each study</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study 1a</td>
<td>Initial: Wrong</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">21.43%</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">40.48%</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">59.52%</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">88.1%</td>
</tr>
<tr class="even">
<td></td>
<td>Initial: Neutral</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">30.95%</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">45.24%</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">19.05%</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">9.52%</td>
</tr>
<tr class="odd">
<td></td>
<td>Initial: ok</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">47.62%</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">14.29%</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">21.43%</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2.38%</td>
</tr>
<tr class="even">
<td></td>
<td>Revised: Wrong</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">23.81%</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">45.24%</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">54.76%</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">88.1%</td>
</tr>
<tr class="odd">
<td></td>
<td>Revised: Neutral</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">28.57%</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">33.33%</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">23.81%</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">11.9%</td>
</tr>
<tr class="even">
<td></td>
<td>Revised: ok</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">47.62%</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">21.43%</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">21.43%</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0%</td>
</tr>
<tr class="odd">
<td>Study 1b</td>
<td>Initial: Wrong</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">84</td>
<td style="text-align: center;">68.29%</td>
</tr>
<tr class="even">
<td></td>
<td>Initial: Neutral</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">17.07%</td>
</tr>
<tr class="odd">
<td></td>
<td>Initial: OK</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">14.63%</td>
</tr>
<tr class="even">
<td></td>
<td>Initial: Wrong</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">65.04%</td>
</tr>
<tr class="odd">
<td></td>
<td>Initial: Neutral</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">22.76%</td>
</tr>
<tr class="even">
<td></td>
<td>Initial: OK</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">12.2%</td>
</tr>
<tr class="odd">
<td>Study 2</td>
<td>Initial: Wrong</td>
<td style="text-align: center;">132</td>
<td style="text-align: center;">70.21%</td>
<td style="text-align: center;">127</td>
<td style="text-align: center;">67.55%</td>
<td style="text-align: center;">117</td>
<td style="text-align: center;">62.23%</td>
<td style="text-align: center;">146</td>
<td style="text-align: center;">77.66%</td>
</tr>
<tr class="even">
<td></td>
<td>Initial: Neutral</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">9.04%</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">9.57%</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">23.94%</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">14.36%</td>
</tr>
<tr class="odd">
<td></td>
<td>Initial: ok</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">19.15%</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">20.74%</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">12.23%</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">6.38%</td>
</tr>
<tr class="even">
<td></td>
<td>Revised: Wrong</td>
<td style="text-align: center;">138</td>
<td style="text-align: center;">73.4%</td>
<td style="text-align: center;">124</td>
<td style="text-align: center;">65.96%</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">58.51%</td>
<td style="text-align: center;">147</td>
<td style="text-align: center;">78.19%</td>
</tr>
<tr class="odd">
<td></td>
<td>Revised: Neutral</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">6.91%</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">12.23%</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">20.74%</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">12.77%</td>
</tr>
<tr class="even">
<td></td>
<td>Revised: ok</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">17.02%</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">19.68%</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">19.15%</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">7.45%</td>
</tr>
<tr class="odd">
<td>Study 3</td>
<td>Initial: Wrong</td>
<td style="text-align: center;">155</td>
<td style="text-align: center;">57.2%</td>
<td style="text-align: center;">151</td>
<td style="text-align: center;">55.72%</td>
<td style="text-align: center;">82</td>
<td style="text-align: center;">30.26%</td>
<td style="text-align: center;">176</td>
<td style="text-align: center;">64.94%</td>
</tr>
<tr class="even">
<td></td>
<td>Initial: Neutral</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">13.65%</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">15.5%</td>
<td style="text-align: center;">99</td>
<td style="text-align: center;">36.53%</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">11.81%</td>
</tr>
<tr class="odd">
<td></td>
<td>Initial: ok</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">13.28%</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">13.28%</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">22.88%</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">8.49%</td>
</tr>
<tr class="even">
<td></td>
<td>Revised: Wrong</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">54.61%</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">51.66%</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">18.82%</td>
<td style="text-align: center;">173</td>
<td style="text-align: center;">63.84%</td>
</tr>
<tr class="odd">
<td></td>
<td>Revised: Neutral</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">13.65%</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">19.56%</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;">35.42%</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">11.07%</td>
</tr>
<tr class="even">
<td></td>
<td>Revised: ok</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">13.65%</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">12.18%</td>
<td style="text-align: center;">91</td>
<td style="text-align: center;">33.58%</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">8.49%</td>
</tr>
</tbody>
</table>
</div>
<p>A paired samples t-test revealed no differences in the ratings of behaviours from time one to time two, <em>Heinz</em>, <em>t</em>(81.979254) = 0.053, <em>p</em> = .958, <em>d</em> = 0.0115954; <em>Cannibal</em>, <em>t</em>(81.8464504) = -0.296, <em>p</em> = .768, <em>d</em> = 0.0644897; <em>Incest</em>, <em>t</em>(81.8102068) = -0.05, <em>p</em> = .960, <em>d</em> = 0.0109172; <em>Trolley</em>, <em>t</em>(81.868551) = -0.164, <em>p</em> = .870, <em>d</em> = 0.0358119.</p>
<p>A one-way ANOVA revealed significant differences in initial judgements depending on scenario, <em>F</em>(3, ,, , 164) = 20.77, <em>p</em> &lt; .001, partial <span class="math inline">\(\eta\)</span><sup>2</sup> = .275. Tukey’s post-hoc pairwise comparison revealed that judgements in the <em>Heinz</em> dilemma were significantly more favourable than for each of the other scenarios: <em>Cannibal</em>, <em>p</em> &lt; .001, <em>Incest</em>, <em>p</em> &lt; .001, <em>Trolley</em>, <em>p</em> = .003; while judgements of <em>Cannibal</em> were significantly more harsh than all other scenarios: <em>Heinz</em>, <em>p</em> &lt; .001, <em>Incest</em>, <em>p</em> = .007. <em>Trolley</em>, <em>p</em> &lt; .001; there was no significant difference between judgements of <em>Incest</em> and of <em>Trolley</em>, <em>p</em> = .762.</p>
<p>A one-way ANOVA revealed the same pattern of differences in revised judgements depending on scenario, <em>F</em>(3, ,, , 164) = 20.19, <em>p</em> &lt; .001, partial <span class="math inline">\(\eta\)</span><sup>2</sup> = .270. Again, Tukey’s post-hoc pairwise comparison revealed that judgements in the <em>Heinz</em> dilemma were significantly more favourable than for each of the other scenarios: <em>Cannibal</em>, <em>p</em> &lt; .001, <em>Incest</em>, <em>p</em> &lt; .001, <em>Trolley</em>, <em>p</em> = .005; while judgements of <em>Cannibal</em> were significantly more harsh than all other scenarios: <em>Heinz</em>, <em>p</em> &lt; .001, <em>Incest</em>, <em>p</em> = .009. <em>Trolley</em>, <em>p</em> &lt; .001; there was no significant difference between judgements of <em>Incest</em> and of <em>Trolley</em>, <em>p</em> = .685.</p>
</section>
<section id="tables-of-other-responses" class="level3">
<h3 class="anchored" data-anchor-id="tables-of-other-responses">Tables of other Responses</h3>
<div class="cell-output-display">

(#tab:tab2other)

<div data-custom-style="Table Caption">
<em>Means and Standard Deviations for initial and revised confidence ratings, and for self-reported changed mind for each scenario for each study</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study 1a</td>
<td>Initial Confidence</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.3</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">1.7</td>
</tr>
<tr class="even">
<td></td>
<td>Revised Confidence</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">6.1</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="odd">
<td></td>
<td>Changed Mind</td>
<td style="text-align: center;">2.7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">1.9</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">2.1</td>
</tr>
<tr class="even">
<td>Study 1b</td>
<td>Initial Confidence</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">4.9</td>
<td style="text-align: center;">1.6</td>
</tr>
<tr class="odd">
<td></td>
<td>Revised Confidence</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">5.1</td>
<td style="text-align: center;">1.7</td>
</tr>
<tr class="even">
<td></td>
<td>Changed Mind</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">1.7</td>
</tr>
<tr class="odd">
<td>Study 2</td>
<td>Initial Confidence</td>
<td style="text-align: center;">5.9</td>
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">5.3</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">1.4</td>
</tr>
<tr class="even">
<td></td>
<td>Revised Confidence</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">1.3</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">1.3</td>
</tr>
<tr class="odd">
<td></td>
<td>Changed Mind</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">1.3</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">1.4</td>
</tr>
<tr class="even">
<td>Study 3</td>
<td>Initial Confidence</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">1.6</td>
</tr>
<tr class="odd">
<td></td>
<td>Revised Confidence</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">5.7</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="even">
<td></td>
<td>Changed Mind</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">1.3</td>
</tr>
</tbody>
</table>
</div>
<div style="page-break-after: always;"></div>
<div class="cell-output-display">

(#tab:tabPostQs)

<div data-custom-style="Table Caption">
<em>Means and Standard Deviations for responses to the post-discussion questionnaire for each scenario for each study</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study 1a</td>
<td>Confused</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">2.1</td>
</tr>
<tr class="even">
<td></td>
<td>Irritated</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">2.9</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">2.5</td>
</tr>
<tr class="odd">
<td></td>
<td>Reason-Based</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">1.8</td>
</tr>
<tr class="even">
<td></td>
<td>Gut-Based</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">2.3</td>
</tr>
<tr class="odd">
<td>Study 1b</td>
<td>Confused</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2.1</td>
</tr>
<tr class="even">
<td></td>
<td>Irritated</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">2.1</td>
</tr>
<tr class="odd">
<td></td>
<td>Reason-Based</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">1.6</td>
</tr>
<tr class="even">
<td></td>
<td>Gut-Based</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">1.9</td>
</tr>
<tr class="odd">
<td>Study 2</td>
<td>Confused</td>
<td style="text-align: center;">1.9</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.4</td>
</tr>
<tr class="even">
<td></td>
<td>Irritated</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">1.9</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">1.9</td>
</tr>
<tr class="odd">
<td></td>
<td>Reason-Based</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">5.1</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">5.1</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">1.9</td>
</tr>
<tr class="even">
<td></td>
<td>Gut-Based</td>
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">3.8</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">2.2</td>
</tr>
<tr class="odd">
<td>Study 3</td>
<td>Confused</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">1.9</td>
<td style="text-align: center;">2.8</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">1.7</td>
</tr>
<tr class="even">
<td></td>
<td>Irritated</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.4</td>
</tr>
<tr class="odd">
<td></td>
<td>Reason-Based</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">5.4</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">1.8</td>
</tr>
<tr class="even">
<td></td>
<td>Gut-Based</td>
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.4</td>
</tr>
</tbody>
</table>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="measuring-dumbfounding" class="level3">
<h3 class="anchored" data-anchor-id="measuring-dumbfounding">Measuring dumbfounding</h3>
<p>Participants who selected the admission of not having reasons were identified as dumbfounded. Across the four scenarios (Study 1a), 21 participants (50%) provided a dumbfounded response at least once. In Study 1b, 47 participants, (38.2113821%) provided a dumbfounded response for the <em>Cannibal</em> scenario. Table&nbsp;@ref(tab:tab2dumb) shows the number and percentage of participants who selected each response for each scenario across Studies 1a and 1b. Figure&nbsp;@ref(fig:chinesefig) shows this information for Study 1a, while Figure&nbsp;@ref(fig:chinesefig2) additionally includes the responses for Study1b. Crucially for the current study, rates of dumbfounded responding for each scenario in Study 1a were significantly greater than zero, <em>Heinz</em>: <em>z</em> = 2.97, <em>p</em> = .003; <em>Trolley</em>: <em>z</em> = 3.17, <em>p</em> = .001; <em>Incest</em>: <em>z</em> = 2.76, <em>p</em> = .006; <em>Cannibal</em>: <em>z</em> = 3.92, <em>p</em> &lt; .001. Similarly rates of dumbfounded responding in Study 1b were significantly greater than zero for the <em>Cannibal</em> scenario, <em>z</em> = 7.62, <em>p</em> &lt; .001.</p>
<div class="cell-output-display">

(#tab:tab2dumb)

<div data-custom-style="Table Caption">
<em>Observed frequency and percentage of each of the responses: dumbfounded, nothing wrong, and reasons provided for each scenario for each study</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study 1a</td>
<td>Nothing wrong</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">33.33%</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">26.19%</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">45.24%</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">11.9%</td>
</tr>
<tr class="even">
<td></td>
<td>Dumbfounded</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">19.05%</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">21.43%</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">16.67%</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">30.95%</td>
</tr>
<tr class="odd">
<td></td>
<td>Reasons</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">47.62%</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">52.38%</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">38.1%</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">57.14%</td>
</tr>
<tr class="even">
<td>Study 1b</td>
<td>Nothing wrong</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">15.45%</td>
</tr>
<tr class="odd">
<td></td>
<td>Dumbfounded</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">38.21%</td>
</tr>
<tr class="even">
<td></td>
<td>Reasons</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">46.34%</td>
</tr>
<tr class="odd">
<td>Study 2</td>
<td>Nothing wrong</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">27.14%</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">22.8%</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">40.71%</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">19%</td>
</tr>
<tr class="even">
<td></td>
<td>Dumbfounded</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">11.4%</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">25.51%</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">17.91%</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">23.88%</td>
</tr>
<tr class="odd">
<td></td>
<td>Reasons</td>
<td style="text-align: center;">112</td>
<td style="text-align: center;">60.79%</td>
<td style="text-align: center;">95</td>
<td style="text-align: center;">51.56%</td>
<td style="text-align: center;">77</td>
<td style="text-align: center;">41.79%</td>
<td style="text-align: center;">106</td>
<td style="text-align: center;">57.53%</td>
</tr>
<tr class="even">
<td>Study 3</td>
<td>Nothing wrong</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">22.14%</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">14.02%</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">62.73%</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">16.97%</td>
</tr>
<tr class="odd">
<td></td>
<td>Dumbfounded</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">12.18%</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">20.66%</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">8.12%</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">16.61%</td>
</tr>
<tr class="even">
<td></td>
<td>Reasons</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">47.97%</td>
<td style="text-align: center;">132</td>
<td style="text-align: center;">48.71%</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">17.71%</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">51.66%</td>
</tr>
</tbody>
</table>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/chinesefig-1.png" class="quarto-discovered-preview-image img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Rates of each type of response for each scenario in the Chinese Sample ( = 42)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/chinesefig2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Rates of each type of response for each scenario in the Chinese Sample (including additional data on Cannibal scenario)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>There was no significant difference in observed rates of dumbfounded responding depending on which scenario was being discussed, <span class="math inline">\(\chi\)</span><sup>2</sup>(6, <em>N</em> = 271) = 12.34, <em>p</em> = .055. Similarly, there was no influence of type of scenario (reasoning vs intuition) on rates of dumbfounded responding <span class="math inline">\(\chi\)</span><sup>2</sup>(2, <em>N</em> = 271) = 0.31, <em>p</em> = .855.</p>
<p>We found clear evidence for dumbfounded responding in our Chinese sample. Interestingly, while the <em>Incest</em> scenario is generally regarded as the most reliable for eliciting moral dumbfounding in Western samples <span class="citation" data-cites="royzman_curious_2015">(e.g., <a href="#ref-royzman_curious_2015" role="doc-biblioref">Royzman, Kim, and Leeman 2015</a>)</span>, <em>Cannibal</em> appeared to be the scenario most likely to elicit dumbfounding in this sample. While this difference in responding to the critical slide is not statistically significant, we did observe significantly harsher judgements for <em>Cannibal</em> than for the other scenarios. The pattern of responding to the critical slide is therefore not surprising. Furthermore, it is possible that the small sample size meant that our study was not sufficiently powered to detect differences in responding to the critical slide. As such, we note that the converging evidence across three measures (initial judgement, revised judgement, and critical slide), point towards issues surrounding death and respect for the dead as being more relevant in this Chinese sample. This is consistent with existing research on the death taboo, and the importance of death in Chinese culture <span class="citation" data-cites="selin_death_2019 wu_cognitive_2011">(e.g., <a href="#ref-selin_death_2019" role="doc-biblioref">Selin and Rakoff 2019</a>; <a href="#ref-wu_cognitive_2011" role="doc-biblioref">Wu and Lu 2011</a>)</span>. This interpretation is further corroborated by analysis of the open-ended responses, with 20 participants (47.62%) providing statements such as “Jennifer eating human flesh is an immoral and uncivilized behaviour”. This suggests that while WEIRD samples appear to be more inclined to moralise, and present as dumbfounded for, the <em>Incest</em> scenario, it appears (from our small and limited sample) that it is the <em>Cannibal</em> scenario that is of greater concern to Chinese participants.</p>
</section>
<section id="individual-differences-study-1a" class="level3">
<h3 class="anchored" data-anchor-id="individual-differences-study-1a">Individual differences (Study 1a)</h3>
<p>A hierarchical linear regression was conducted to test the possible relationship between ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>, and susceptibility to dumbfounding. Susceptibility to dumbfounding was operationalised by creating a new variable representing the number of times each participant provided a dumbfounded response. This measure was included as our outcome variable, and the four sub-scales of ICS were included as predictor variables. The overall model did not significantly predict susceptibility to dumbfounding <span class="math inline">\(R^2 = .09\)</span>, <span class="math inline">\(F(4, 37) = 0.95\)</span>, <span class="math inline">\(p = .448\)</span>.</p>
<p>We conducted a series of multinomial logistic regressions to investigate the possible relationship between ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> and responding to each of the scenarios individually. Response to the critical slide scenario was the dependent variable for each scenario, and the four sub-scales of the ICS were included as predictor variables.</p>
<p>The overall model did not significantly predict responses for the <em>Heinz</em> dilemma, <span class="math inline">\(\chi\)</span><sup>2</sup>(8, <em>N</em> = 42) = 10.48, <em>p</em> = .233, the observed power was 0.61; neither did the model significantly predict responses for the <em>Trolley</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(8, <em>N</em> = 42) = 11.02, <em>p</em> = .201, the observed power was 0.64; the <em>Incest</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(8, <em>N</em> = 42) = 13.92, <em>p</em> = .084, the observed power was 0.76; nor the <em>Cannibal</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(8, <em>N</em> = 42) = 6.84, <em>p</em> = .554, the observed power was 0.41.</p>
</section>
<section id="individual-differences-study-1b" class="level3">
<h3 class="anchored" data-anchor-id="individual-differences-study-1b">Individual differences (Study 1b)</h3>
<p>Given the larger sample size in Study 1b, we additionally tested if ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> predicted responses to the <em>Cannibal</em> scenario in Study 1b. We conducted a multinomial logistic regression with response to the critical slide as the outcome variable and the four sub-scales of the ICS entered as predictor variables. Overall the model did not significantly predict responses to the critical slide for the <em>Cannibal</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(8, <em>N</em> = 123) = 10.96, <em>p</em> = .204, the observed power was 0.64.</p>
</section>
</section>
</section>
<section id="study-2---indian-sample" class="level1">
<h1>Study 2 - Indian Sample</h1>
<p>Having demonstrated dumbfounded responding in a Chinese context, the aim of Study 2 was to assess if dumbfounded responding can be elicited in an Indian context.</p>
<section id="method-1" class="level2">
<h2 class="anchored" data-anchor-id="method-1">Method</h2>
<section id="participants-and-design-1" class="level3">
<h3 class="anchored" data-anchor-id="participants-and-design-1">Participants and design</h3>
<p>Study 2 was a frequency based attempted replication of <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span>. The aim of Study 2 was to identify if dumbfounded responding could be evoked in an Indian context.</p>
<p>A total sample of 188 (116 female, 69 male, 0 other, 3 declined to report their gender; <em>M<sub>age</sub></em> = 22.88, min = 16, max = 39, <em>SD</em> = 2.55) participants took part. The breakdown of participants’ religion is as follows, Hinduism: <em>n</em> = 138, Islam: <em>n</em> = 4, Christianity: <em>n</em> = 7, Sikhism: <em>n</em> = 4, Buddhism: <em>n</em> = 0, Jainism: <em>n</em> = 8, other: <em>n</em> = 10, and 17 participants declined to provide their religion. All participants were of Indian nationality, and 164 indicated that they resided in India at the time of completing the survey. Participants were recruited through snowball sampling.</p>
</section>
<section id="procedure-and-materials-1" class="level3">
<h3 class="anchored" data-anchor-id="procedure-and-materials-1">Procedure and materials</h3>
<p>The procedure for Study 2 was the same as for Study 1, with some minor changes. Given the diversity of languages in India, and the high proficiency of English among Indian nationals, all written materials were presented in English. The survey was programmed and presented using Qualtrics. The demographic information recorded additionally included religion, given the prominence and diversity of religions in Indian society. We also included the meaning in life questionnaire <span class="citation" data-cites="steger_understanding_2008">(MLQ: <a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span> in Study 2. The entire study lasted twenty to twenty-five minutes.</p>
</section>
</section>
<section id="results-and-discussion-1" class="level2">
<h2 class="anchored" data-anchor-id="results-and-discussion-1">Results and Discussion</h2>
<section id="judgements-of-the-scenarios-1" class="level3">
<h3 class="anchored" data-anchor-id="judgements-of-the-scenarios-1">Judgements of the scenarios</h3>
<p>The mean initial ratings for each scenario were as follows: <em>M<sub>Heinz</sub></em> = 2.61, <em>SD<sub>Heinz</sub></em> = 1.88; <em>M<sub>Cannibal</sub></em> = 2.1, <em>SD<sub>Cannibal</sub></em> = 1.52; <em>M<sub>Incest</sub></em> = 2.66, <em>SD<sub>Incest</sub></em> = 1.84; <em>M<sub>Trolley</sub></em> = 2.83, <em>SD<sub>Trolley</sub></em> = 1.84. The mean revised ratings for each scenario are as follows: <em>M<sub>Heinz</sub></em> = 2.66, <em>SD<sub>Heinz</sub></em> = 1.84; <em>M<sub>Cannibal</sub></em> = 2.15, <em>SD<sub>Cannibal</sub></em> = 1.5; <em>M<sub>Incest</sub></em> = 2.94, <em>SD<sub>Incest</sub></em> = 1.94; <em>M<sub>Trolley</sub></em> = 2.84, <em>SD<sub>Trolley</sub></em> = 1.81. The proportion of wrong, neutral, and ok, judgements for each scenario are displayed in Table&nbsp;@ref(tab:tab2judge).</p>
<p>A paired samples t-test revealed no differences in the ratings of behaviours from time one to time two, <em>Heinz</em>, <em>t</em>(365.9540429) = -0.26, <em>p</em> = .795, <em>d</em> = 0.0270679; <em>Cannibal</em>, <em>t</em>(367.9546849) = -0.31, <em>p</em> = .757, <em>d</em> = 0.0322612; <em>Incest</em>, <em>t</em>(367.0415483) = -1.403, <em>p</em> = .161, <em>d</em> = 0.1459137; <em>Trolley</em>, <em>t</em>(365.8881139) = -0.057, <em>p</em> = .954, <em>d</em> = 0.0059546.</p>
<p>A one-way ANOVA revealed significant differences in initial judgements depending on scenario, <em>F</em>(3, ,, , 735) = 5.72, <em>p</em> &lt; .001, partial <span class="math inline">\(\eta\)</span><sup>2</sup> = .023. Tukey’s post-hoc pairwise comparison revealed that judgements of <em>Cannibal</em> were significantly more harsh than all other scenarios: <em>Heinz</em>, <em>p</em> = .033, <em>Incest</em>, <em>p</em> = .013. <em>Trolley</em>, <em>p</em> &lt; .001; there were no significant differences in the ratings of the other scenarios, <em>Heinz</em>/<em>Incest</em>, <em>p</em> = .988, <em>Heinz</em>/<em>Trolley</em>, <em>p</em> = .631, <em>Incest</em>/<em>Trolley</em>, <em>p</em> = .819.</p>
<p>A one-way ANOVA revealed the same pattern of differences in revised judgements depending on scenario, <em>F</em>(3, ,, , 733) = 7.17, <em>p</em> &lt; .001, partial <span class="math inline">\(\eta\)</span><sup>2</sup> = .029. Again, Tukey’s post-hoc pairwise comparison revealed that judgements of <em>Cannibal</em> were significantly more harsh than all other scenarios: <em>Heinz</em>, <em>p</em> = .034, <em>Incest</em>, <em>p</em> &lt; .001. <em>Trolley</em>, <em>p</em> = .001; there were no significant differences in the ratings of the other scenarios, <em>Heinz</em>/<em>Incest</em>, <em>p</em> = .416, <em>Heinz</em>/<em>Trolley</em>, <em>p</em> = .763, <em>Incest</em>/<em>Trolley</em>, <em>p</em> = .944.</p>
</section>
<section id="measuring-dumbfounding-1" class="level3">
<h3 class="anchored" data-anchor-id="measuring-dumbfounding-1">Measuring dumbfounding</h3>
<p>Participants who selected the admission of not having reasons were identified as dumbfounded. Across the four scenarios 90 participants (49.1803279%) provided a dumbfounded response at least once. Table&nbsp;@ref(tab:tab2dumb) and Figure&nbsp;@ref(fig:indiafig) show the number and percentage of participants who selected each response for each scenario. Rates of dumbfounded responding for each scenario in Study 2 were significantly greater than zero, <em>Heinz</em>: <em>z</em> = 4.6, <em>p</em> &lt; .001; <em>Trolley</em>: <em>z</em> = 7.35, <em>p</em> &lt; .001; <em>Incest</em>: <em>z</em> = 6.03, <em>p</em> &lt; .001; <em>Cannibal</em>: <em>z</em> = 7.08, <em>p</em> &lt; .001, thus providing evidence for moral dumbfounding in our Indian sample. To test fot the possibility of order effects, we conducted a chi-square test for independence which revealed no significant differences in responses to the critical slide depending on when the scenario was presented, <span class="math inline">\(\chi\)</span><sup>2</sup>(6, <em>N</em> = 183) = 8, <em>p</em> = .238.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/indiafig-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Rates of each type of response for each scenario in the Indian Sample ( = 181)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A chi-square test for independence revealed significant differences in responses to the critical slide depending on which scenario was being discussed, <span class="math inline">\(\chi\)</span><sup>2</sup>(6, <em>N</em> = 183) = 36.86, <em>p</em> &lt; .001. Table&nbsp;@ref(tab:tabchisq1) shows the observed counts, expected counts and standardised residuals for each response for each scenario. For <em>Heinz</em>, people were significantly better at providing reasons, and significantly less likely to present as dumbfounded; while people were significantly more likely to be dumbfounded by <em>Trolley</em> than expected; for <em>Incest</em>, people were significantly less likely to provide reasons, and significantly more likely to select “There is nothing wrong” than expected; finally for <em>Cannibal</em> significantly fewer than expected selected “There is nothing wrong”.</p>
<p>The observed variability was not related to the type of scenario (intuition vs reasoning), with no relationship between type of scenario and response to the critical slide being observed, <span class="math inline">\(\chi\)</span><sup>2</sup>(2, <em>N</em> = 183) = 3.63, <em>p</em> = .163.</p>
<div class="cell-output-display">

(#tab:tabchisq1)

<div data-custom-style="Table Caption">
<em>Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on Scenario</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Response</th>
<th></th>
<th style="text-align: center;">Heinz</th>
<th style="text-align: center;">Trolley</th>
<th style="text-align: center;">Incest</th>
<th style="text-align: center;">Cannibal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nothing Wrong</td>
<td>Observed count</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>Expected count</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">51</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>Standardised residuals</td>
<td style="text-align: center;">-0.03</td>
<td style="text-align: center;">-1.61</td>
<td style="text-align: center;">4.63**</td>
<td style="text-align: center;">-2.99*</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dumbfounded</td>
<td>Observed count</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">44</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>Expected count</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>Standardised residuals</td>
<td style="text-align: center;">-3.22*</td>
<td style="text-align: center;">2.31*</td>
<td style="text-align: center;">-0.73</td>
<td style="text-align: center;">1.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reason</td>
<td>Observed count</td>
<td style="text-align: center;">112</td>
<td style="text-align: center;">95</td>
<td style="text-align: center;">77</td>
<td style="text-align: center;">106</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>Expected count</td>
<td style="text-align: center;">97</td>
<td style="text-align: center;">97</td>
<td style="text-align: center;">98</td>
<td style="text-align: center;">98</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>Standardised residuals</td>
<td style="text-align: center;">2.59*</td>
<td style="text-align: center;">-0.4</td>
<td style="text-align: center;">-3.56**</td>
<td style="text-align: center;">1.38</td>
</tr>
</tbody>
</table>
<div data-custom-style="Compact">
<p><em>Note.</em> * = sig. at &lt; .05; ** = sig. at &lt; .001</p>
</div>
<p>&nbsp;</p>
</div>
<p>Study 2 provided evidence that dumbfounded responding can be elicited in an Indian sample. Interestingly, the <em>Cannibal</em> appeared to be of more concern to the participants in this sample than the <em>Incest</em> scenario. Indeed, the proportion of participants selecting “there is nothing wrong” for the <em>Incest</em> scenario was significantly higher (75 participants; 40.7055631%) than for the other scenarios. This also appears to be higher than reported in previous studies involving WEIRD samples, however there is notable fluctuation in the selecting of this response for the <em>Incest</em> scenario, ranging from 16.7% <span class="citation" data-cites="mchugh_searching_2017a">(<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>, Study 3a)</span> to 32.4% <span class="citation" data-cites="mchugh_reasons_2020">(<a href="#ref-mchugh_reasons_2020" role="doc-biblioref">McHugh et al. 2020</a>, Study 2)</span>. Regarding the <em>Cannibal</em> scenario, it appears the relative importance of death observed in Study 1 is similarly present in our Study 2 sample, pointing towards potentially important cultural differences that should be considered in future studies.</p>
</section>
<section id="individual-differences" class="level3">
<h3 class="anchored" data-anchor-id="individual-differences">Individual differences</h3>
<p>A hierarchical linear regression was conducted to test the possible relationship between ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>, MLQ <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span>, and susceptibility to dumbfounding. As in Study 1a, we created a new variable by calculating the number of times each participant provided a dumbfounded response, and used this variable as a measure of participants’ susceptibility to dumbfounding. This measure was our outcome variable, and the four sub-scales of ICS, along with both sub-scales of the MLQ, were included as predictor variables. The overall model was a significant predictor of susceptibility to dumbfounding <span class="math inline">\(R^2 = .08\)</span>, <span class="math inline">\(F(6, 176) = 2.42\)</span>, <span class="math inline">\(p = .029\)</span>, with Vertical Individualism as the only variable making a significant contribution to the model, <span class="math inline">\(b = -0.02\)</span>, 95% CI <span class="math inline">\([-0.05, 0.00]\)</span>, <span class="math inline">\(t(176) = -2.03\)</span>, <span class="math inline">\(p = .044\)</span>, see Table&nbsp;@ref(tab:regressiontable).</p>
<div class="cell-output-display">

(#tab:regressiontable)

<div data-custom-style="Table Caption">
<em>Study 2: Predictors of susceptibility to moral dumbfounding</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;"><span class="math inline">\(b\)</span></th>
<th style="text-align: left;">95% CI</th>
<th style="text-align: left;"><span class="math inline">\(t\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\mathit{df}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(p\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">1.62</td>
<td style="text-align: left;">[0.51, 2.72]</td>
<td style="text-align: left;">2.88</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.004</td>
</tr>
<tr class="even">
<td style="text-align: left;">VC</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">[0.00, 0.05]</td>
<td style="text-align: left;">1.96</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HC</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">[-0.03, 0.03]</td>
<td style="text-align: left;">-0.14</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.886</td>
</tr>
<tr class="even">
<td style="text-align: left;">VI</td>
<td style="text-align: left;">-0.02</td>
<td style="text-align: left;">[-0.05, 0.00]</td>
<td style="text-align: left;">-2.03</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.044</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HI</td>
<td style="text-align: left;">-0.03</td>
<td style="text-align: left;">[-0.06, 0.00]</td>
<td style="text-align: left;">-1.75</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.082</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLQ Presence</td>
<td style="text-align: left;">-0.01</td>
<td style="text-align: left;">[-0.04, 0.01]</td>
<td style="text-align: left;">-1.21</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.229</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MLQ Search</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">[-0.02, 0.04]</td>
<td style="text-align: left;">0.92</td>
<td style="text-align: left;">176</td>
<td style="text-align: left;">.361</td>
</tr>
</tbody>
</table>
</div>
<p>We conducted a series of logistic regressions to investigate the possible relationship between ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> and responding to each of the scenarios individually. Response to the critical slide scenario was the dependent variable for each scenario, and the four sub-scales of the ICS were included as predictor variables.</p>
<p>The overall model did not significantly predict responses for the <em>Heinz</em> dilemma, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 183) = 13.68, <em>p</em> = .322, the observed power was 0.67; neither did the model significantly predict responses for the <em>Trolley</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 183) = 14.43, <em>p</em> = .274, the observed power was 0.7.</p>
<p>Interestingly, the overall model significantly predicted responses for the <em>Incest</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 183) = 26.33, <em>p</em> = .010, the observed power was 0.95. The overall model explained between 10.68% (Cox and Snell R square) and 14.43% (Nadelkerke R squared) of the variance in responses to the critical slide. The only significant predictors in the model were Horizontal Individualism, and Vertical Collectivism. As HI increased, participants were significantly more likely to select “there is nothing wrong” than to provide reasons for their judgement, Wald = 7.44, <em>p</em> = .006, odds ratio = 1.1097603, 95% CI [1.0297624, 1.1959729]. As VC increased, participants were significantly more likely to present as dumbfounded than to provide reasons, Wald = 5.01, <em>p</em> = .025, odds ratio = 0.9151576, 95% CI [0.8467967, 1.0036718].</p>
<p>The overall model also significantly predicted responses for the <em>Cannibal</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 183) = 24.63, <em>p</em> = .017, the observed power was 0.94. The overall model explained between 7.16% (Cox and Snell R square) and 11.49% (Nadelkerke R squared) of the variance in responses to the critical slide. Meaning in Life: Presence <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span> was the only significant predictor in the model, as Meaning in Life: Presence, increased, participants were significantly more likely provide reasons than to present as dumbfounded, Wald = 5.81, <em>p</em> = .016, odds ratio = 0.9258257, 95% CI [0.8695836, 0.9857055].</p>
</section>
</section>
</section>
<section id="study-3---mixed-sample" class="level1">
<h1>Study 3 - Mixed Sample</h1>
<p>Having demonstrated dumbfounded responding in targeted samples in two different countries, the aim of Study 3 was to investigate if dumbfounded responding could be elicited in a more diverse sample recruited from a range of non-WEIRD countries.</p>
<section id="method-2" class="level2">
<h2 class="anchored" data-anchor-id="method-2">Method</h2>
<section id="participants-and-design-2" class="level3">
<h3 class="anchored" data-anchor-id="participants-and-design-2">Participants and design</h3>
<p>Study 3 was a frequency based attempted replication of <span class="citation" data-cites="mchugh_searching_2017a">McHugh et al. (<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">2017</a>)</span>. The aim of Study 3 was to identify if dumbfounded responding could be evoked in a mixed sample of participants from a selection of non-WEIRD countries, primarily North Africa and the Middle East.</p>
<p>An initial sample of four-hundred-and-sixty-three participants were recruited for Study 3. Some participants did not provide full responses for all four scenarios (the total number of participants who completed the Critial Slide for all four scenarios was <em>n</em> = 203. In removing participants with missing data, we retained all participants who completed the Critical Slide for at least one scenario. Following this, we were left with a total sample of <em>N</em> = 282 (171 female, 103 male, 3 other, 5 declined to report their gender; <em>M<sub>age</sub></em> = 27.71, min = 18, max = 68, <em>SD</em> = 12.46).</p>
<div class="cell-output-display">

(#tab:tabcountries)

<div data-custom-style="Table Caption">
<em>Participants by Country</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: left;">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Algeria</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bahrain</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bangladesh</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Egypt</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">india</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">India</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">indiam</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IndiSan</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iran</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iraq</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Israel</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jordan</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kuwait</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lebanon</td>
<td style="text-align: left;">34</td>
</tr>
<tr class="even">
<td style="text-align: left;">Libya</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Morocco</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oman</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pakistan</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Palestine</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philippines</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saudi Arabia</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Africa</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sri Lankan</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sudan</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Syria</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">UAE</td>
<td style="text-align: left;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yemen</td>
<td style="text-align: left;">1</td>
</tr>
</tbody>
</table>
</div>
<p>Our target sample was participants from non-WEIRD countries. As such we removed 11 participants who reported being from the UK (<em>n</em> = 3), USA (<em>n</em> = 1), Canada (<em>n</em> = 2), Germany (<em>n</em> = 1), Portugal (<em>n</em> = 1), Netherlands (<em>n</em> = 1), and participants who did not provide a country of origin (<em>n</em> = 2). This left a total sample of <em>N</em> = 271 (165 female, 98 male, 3 other, 5 declined to report their gender; <em>M<sub>age</sub></em> = 27.75, min = 18, max = 68, <em>SD</em> = 12.32). The breakdown of participants’ nationalities is displayed in Table&nbsp;@ref(tab:tabcountries). The breakdown of participants’ religions is as follows, Islam: <em>n</em> = 176, Christianity: <em>n</em> = 49, Hinduism: <em>n</em> = 10, other: <em>n</em> = 21, and 15 participants declined to provide their religion.</p>
</section>
<section id="procedure-and-materials-2" class="level3">
<h3 class="anchored" data-anchor-id="procedure-and-materials-2">Procedure and materials</h3>
<p>The procedure for Study 3 was largely the same as Study 2, with some key changes. Data collection was conducted in collaboration with the Middlesex University Dubai, and participants were recruited through opportunity and snowball sampling by undergraduate students in the University. Given the potentially sensitive and offensive nature of some of the traditional dumbfounding scenarios (<em>Incest</em> and <em>Cannibal</em>), we replaced these scenarios with scenarios less likely to cause offence: <em>Promise</em> and <em>Dog</em> (see Appendix A).</p>
<p>The survey was programmed and presented using Qualtrics. The demographic information recorded additionally included participants’ nationality. We also included a filter question in an attempt to limit participation to participants from non-WEIRD countries. As in Study 2, we also included the meaning in life questionnaire <span class="citation" data-cites="steger_understanding_2008">(MLQ: <a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span> and ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>. The entire study lasted twenty to twenty-five minutes.</p>
</section>
</section>
<section id="results-and-discussion-2" class="level2">
<h2 class="anchored" data-anchor-id="results-and-discussion-2">Results and Discussion</h2>
<section id="judgements-of-the-scenarios-2" class="level3">
<h3 class="anchored" data-anchor-id="judgements-of-the-scenarios-2">Judgements of the scenarios</h3>
<p>The mean initial ratings for each scenario were as follows: <em>M<sub>Heinz</sub></em> = 2.68, <em>SD<sub>Heinz</sub></em> = 1.78; <em>M<sub>Dog</sub></em> = 2.15, <em>SD<sub>Dog</sub></em> = 1.76; <em>M<sub>Promise</sub></em> = 3.88, <em>SD<sub>Promise</sub></em> = 1.65; <em>M<sub>Trolley</sub></em> = 2.61, <em>SD<sub>Trolley</sub></em> = 1.88. The mean revised ratings for each scenario are as follows: <em>M<sub>Heinz</sub></em> = 2.84, <em>SD<sub>Heinz</sub></em> = 1.74; <em>M<sub>Dog</sub></em> = 2.21, <em>SD<sub>Dog</sub></em> = 1.79; <em>M<sub>Promise</sub></em> = 4.37, <em>SD<sub>Promise</sub></em> = 1.65; <em>M<sub>Trolley</sub></em> = 2.86, <em>SD<sub>Trolley</sub></em> = 1.87. The proportion of wrong, neutral, and ok, judgements for each scenario are displayed in Table&nbsp;@ref(tab:tab2judge).</p>
<p>A paired samples t-test revealed no differences in the ratings of behaviours from time one to time two for <em>Heinz</em>, <em>t</em>(447.9965543) = -0.979, <em>p</em> = .328, <em>d</em> = 0.0922583; <em>Dog</em>, <em>t</em>(454.4625702) = -0.367, <em>p</em> = .714, <em>d</em> = 0.0342957; or <em>Trolley</em>, <em>t</em>(452.9942137) = -1.456, <em>p</em> = .146, <em>d</em> = 0.1365021. In contrast, participants revised ratings of <em>Promise</em> (<em>M</em> = 4.37, <em>SD</em> = 1.65) were significantly more favourable than their initial ratings <em>M</em> = 3.88, <em>SD</em> = 1.65, <em>t</em>(478.8640634) = -3.276, <em>p</em> = .001, <em>d</em> = 0.2987195</p>
<p>A one-way ANOVA revealed significant differences in initial judgements depending on scenario, <em>F</em>(3, ,, , 927) = 41.37, <em>p</em> &lt; .001, partial <span class="math inline">\(\eta\)</span><sup>2</sup> = .118. Tukey’s post-hoc pairwise comparison revealed that judgements of <em>Promise</em> were significantly more favourable than all other scenarios: <em>Heinz</em>, <em>p</em> &lt; .001, <em>Dog</em>, <em>p</em> &lt; .001. <em>Trolley</em>, <em>p</em> &lt; .001; <em>Heinz</em> was rated significantly more favourably than <em>Dog</em>, = .009 there were no significant differences in the ratings of the other scenarios, <em>Heinz</em>/<em>Trolley</em>, <em>p</em> = .976, <em>Dog</em>/<em>Trolley</em>, <em>p</em> = .030.</p>
<p>A one-way ANOVA revealed a similar pattern of differences in revised judgements depending on scenario, <em>F</em>(3, ,, , 908) = 63.46, <em>p</em> &lt; .001, partial <span class="math inline">\(\eta\)</span><sup>2</sup> = .173. Again, Tukey’s post-hoc pairwise comparison revealed that judgements of <em>Promise</em> were significantly more favourable than all other scenarios: <em>Heinz</em>, <em>p</em> &lt; .001, <em>Dog</em>, <em>p</em> &lt; .001. <em>Trolley</em>, <em>p</em> &lt; .001; and judgements of <em>Dog</em> were significantly more harsh than both <em>Heinz</em>, <em>p</em> = .001 and <em>Trolley</em>, <em>p</em> &lt; .001; all there were no significant differences in ratings of <em>Heinz</em> and <em>Trolley</em>, <em>p</em> = .999.</p>
</section>
<section id="measuring-dumbfounding-2" class="level3">
<h3 class="anchored" data-anchor-id="measuring-dumbfounding-2">Measuring dumbfounding</h3>
<p>Participants who selected the admission of not having reasons were identified as dumbfounded. Across the four scenarios 109 participants (40.2214022%) provided a dumbfounded response at least once. Table&nbsp;@ref(tab:tab2dumb) and Figure&nbsp;@ref(fig:study3fig) show the number and percentage of participants who selected each response for each scenario. Rates of dumbfounded responding for each scenario in Study 2 were significantly greater than zero, <em>Heinz</em>: <em>z</em> = 5.68, <em>p</em> &lt; .001; <em>Trolley</em>: <em>z</em> = 7.36, <em>p</em> &lt; .001; <em>Promise</em>: <em>z</em> = 4.81, <em>p</em> &lt; .001; <em>Dog</em>: <em>z</em> = 6.68, <em>p</em> &lt; .001, thus providing evidence for moral dumbfounding in our MENA sample. To test for the possibility of order effects, we conducted a chi-square test for independence which revealed no significant differences in responses to the critical slide depending on when the scenario was presented, <span class="math inline">\(\chi\)</span><sup>2</sup>(6, <em>N</em> = 271) = 3.92, <em>p</em> = .687.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/study3fig-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Rates of each type of response for each scenario in the Mixed Sample</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A chi-square test for independence revealed significant differences in responses to the critical slide depending on which scenario was being discussed, <span class="math inline">\(\chi\)</span><sup>2</sup>(6, <em>N</em> = 271) = 205.55, <em>p</em> &lt; .001. Table&nbsp;@ref(tab:tabchisq1b) shows the observed counts, expected counts and standardised residuals for each response for each scenario. For <em>Heinz</em>, <em>Dog</em>, and <em>Trolley</em>, people were significantly more likely to provide reasons than to select “there is nothing wrong”. In contrast, for <em>Promise</em> participants were more likely to select “there is nothing wrong” than to present as dumbfounded, or to present as dumbfounded or provide reasons. We note that this finding may have been confounded by the responses to <em>Promise</em>, however the result holds when <em>Promise</em> is excluded from the analysis, <span class="math inline">\(\chi\)</span><sup>2</sup>(4, <em>N</em> = 271) = 11.48, <em>p</em> &lt; .001. Study 3 provided further evidence that dumbfounded responding can be elicited in a non-WEIRD sample. Furthermore, the use of alternative scenarios provide evidence that moral dumbfounding can be elicited by a broader range of scenarios than normally demonstrated in the existing literature.</p>
<div class="cell-output-display">

(#tab:tabchisq1b)

<div data-custom-style="Table Caption">
<em>Observed counts, expected counts, and standardised residuals for each response to the critical slide depending on Scenario</em>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Response</th>
<th></th>
<th style="text-align: center;">Dog</th>
<th style="text-align: center;">Heinz</th>
<th style="text-align: center;">Promise</th>
<th style="text-align: center;">Trolley</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nothing Wrong</td>
<td>Observed count</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>Expected count</td>
<td style="text-align: center;">79</td>
<td style="text-align: center;">76</td>
<td style="text-align: center;">82</td>
<td style="text-align: center;">77</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>Standardised residuals</td>
<td style="text-align: center;">-5.27**</td>
<td style="text-align: center;">-2.61*</td>
<td style="text-align: center;">13.95**</td>
<td style="text-align: center;">-6.32**</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dumbfounded</td>
<td>Observed count</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">56</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>Expected count</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>Standardised residuals</td>
<td style="text-align: center;">1.18</td>
<td style="text-align: center;">-0.99</td>
<td style="text-align: center;">-3.74**</td>
<td style="text-align: center;">3.61**</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reason</td>
<td>Observed count</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">132</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>Expected count</td>
<td style="text-align: center;">113</td>
<td style="text-align: center;">109</td>
<td style="text-align: center;">117</td>
<td style="text-align: center;">111</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>Standardised residuals</td>
<td style="text-align: center;">4.11**</td>
<td style="text-align: center;">3.22*</td>
<td style="text-align: center;">-10.42**</td>
<td style="text-align: center;">3.29*</td>
</tr>
</tbody>
</table>
<div data-custom-style="Compact">
<p><em>Note.</em> * = sig. at &lt; .05; ** = sig. at &lt; .001</p>
</div>
<p>&nbsp;</p>
</div>
</section>
<section id="individual-differences-1" class="level3">
<h3 class="anchored" data-anchor-id="individual-differences-1">Individual differences</h3>
<p>A hierarchical linear regression was conducted to test the possible relationship between ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>, MLQ <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span>, and susceptibility to dumbfounding. As in Studies 1 and 2, susceptibility to dumbfounding was operationalized by calculating the number of times a participant provided a dumbfounded response. With this measure as the outcome variable, we included the four sub-scales of ICS, along with both sub-scales of the MLQ, as predictor variables in a multinomial logistic regression model. The overall model was not a significant predictor of susceptibility to dumbfounding <span class="math inline">\(R^2 = .06\)</span>, <span class="math inline">\(F(6, 179) = 2.03\)</span>, <span class="math inline">\(p = .064\)</span> in Study 3.</p>
<p>We conducted a series of logistic regressions to investigate the possible relationship between ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> and MLQ <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span>, and responding to each of the scenarios individually. Response to the critical slide scenario was the dependent variable for each scenario, and the four sub-scales of the ICS, along with the two sub-scales of the MLQ were included as predictor variables.</p>
<p>The overall model predicted responses for the <em>Heinz</em> dilemma, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 205) = 22.7, <em>p</em> = .030, the observed power was 0.91. neither did the model significantly predict responses for the <em>Trolley</em> scenario, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 205) = 13.45, <em>p</em> = .337, the observed power was 0.66. The overall model explained between 6.94% (Cox and Snell R square) and 10.25% (Nadelkerke R squared) of the variance in responses to the critical slide. The only significant predictors in the model were Vertical Individualism, and Meaning in Life: Search. As VI increased, participants were significantly more likely to select “there is nothing wrong” than to provide reasons for their judgement, Wald = 6.3, <em>p</em> = .377, odds ratio = 0.9733865, 95% CI [1.0151915, 1.1302198]. As Meaning in Life: Search increased, participants were significantly more likely to present as dumbfounded than to provide reasons, Wald = 5.23, <em>p</em> = .638, odds ratio = 1.0216129, 95% CI [1.0116615, 1.1621541].</p>
<p>The overall models did not significantly predict responses for any of the other scenarios: <em>Trolley</em>, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 195) = 13.45, <em>p</em> = .337, the observed power was 0.66; <em>Promise</em>, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 195) = 18.27, <em>p</em> = .108, the observed power was 0.83; <em>Dog</em>, <span class="math inline">\(\chi\)</span><sup>2</sup>(12, <em>N</em> = 195) = 9.43, <em>p</em> = .666, the observed power was 0.48.</p>
</section>
</section>
</section>
<section id="general-discussion" class="level1">
<h1>General Discussion</h1>
<p>The primary aim of the current studies was to investigate if moral dumbfounding is present in non-WEIRD samples. Across three studies, we adopted previously standardised materials and procedure for eliciting and measuring moral dumbfounding <span class="citation" data-cites="mchugh_searching_2017a">(<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>)</span>, and tested whether dumbfounded responding could be elicited in a Chinese sample (Study 1), in an Indian Sample (Study 2), and a mixed sample (Study 3). In order to minimise ambiguity and increase confidence in our results, we employed a conservative measure of dumbfounded responding in all three studies. Participants were only identified as dumbfounded if they admitted to not having reasons for their judgement. Using this conservative measure, we found evidence for moral dumbfounding in all three samples. Our studies are the first to elicit dumbfounded responding in a non-WEIRD context, demonstrating that moral dumbfounding is not unique to WEIRD samples, and providing further evidence that dumbfounding is indeed a real phenomenon.</p>
<p>Study 1 showed no significant variation in rates of dumbfounded responding depending on scenario in our Chinese sample - though this may be due to an underpowered small sample.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> In Study 2 we found significant variability in responding depending on scenario, with lower rates of dumbfounding for <em>Heinz</em>. In Study 3, using different scenarios, we again found significant variability depending on scenario. Interestingly, in Study 2, we found higher rates of dumbfounding of <em>Trolley</em>, whereas previous research involving WEIRD samples has found <em>Cannibal</em> and <em>Incest</em> to be more likely to elicit dumbfounded responding than <em>Trolley</em> <span class="citation" data-cites="mchugh_searching_2017a">(<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>)</span>. This provides some evidence that there may be cultural differences in the types of scenarios that lead to dumbfounding. This cultural variation is interesting and warrants further study for two reasons: (a) different cultures appear to evaluate moral content differently; (b) moral dumbfounding does not appear to be content specific, that is, some scenarios elicit higher rates of moral dumbfounding in some cultures, while in other cultures different scenarios appear to elicit higher rates of moral dumbfounding. Understanding this cultural variability may provide an insight into how different moral content may lead to dumbfounding which in turn could inform our understanding of the cognitive processes that underlie moral dumbfounding, and moral judgement more generally.</p>
<section id="individual-differences-and-dumbfounded-responding" class="level2">
<h2 class="anchored" data-anchor-id="individual-differences-and-dumbfounded-responding">Individual Differences and Dumbfounded Responding</h2>
<p>In addition to testing for the existence of moral dumbfounding in non-WEIRD samples, we investigated the possible relationship between dumbfounded responding and ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>: Studies 1 and 2)</span> and MLQ <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>: Study 2)</span>. Study 1 revealed no significant relationship between ICS and (a) overall susceptibility to dumbfounding, or (b) responses for each scenario individually.</p>
<p>In Study 2 we found that Vertical Individualism <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> was related to susceptibility to dumbfounded responding, with those scoring high in Vertical Individualism, being less likely to present as dumbfounded. It is possible that this observed relationship emerged as a result of participants’ relative motivations to do well in the task of providing reasons. Previous research <span class="citation" data-cites="mchugh_searching_2017a">(<a href="#ref-mchugh_searching_2017a" role="doc-biblioref">McHugh et al. 2017</a>)</span> provides suggestive evidence that a dumbfounded response is aversive, that people are motivated to appear consistent. This consistency can be successfully achieved by providing a reason for a judgement, or by revising a judgement and selecting “there is nothing wrong”. In contrast, providing a dumbfounded response may be seen as failing to present as consistent. The items in the Vertical Individualism sub-scale appear to provide a measure of people’s motivations to do well in relation to others (e.g., “It is important that I do my job better than others”; “When another person does better than I do, I get tense and aroused”). However, it is possible that this sub-scale additionally provides an indication of people’s motivations for success (e.g., “Winning is everything”). As such people who are more motivated to “succeed” in general, may be more motivated to avoid the perceived failure associated with a dumbfounded response. This interpretation is merely speculative, and follow up studies should investigate this in more detail.</p>
<p>In Study 2 we also found evidence that responses to specific scenarios were related to to the individual difference variables measured. Responses to the <em>Incest</em> scenario were predicted by Horizontal Individualism, and Vertical Collectivism <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>. It is possible that this relationship emerges as a result of the <em>content</em> of the scenario rather than providing an insight into the cognitive processes involved in moral dumbfounding. Participants scoring higher in Horizontal Individualism were more likely to select “There is nothing wrong” than to provide a reason for their judgement. It appears that HI is linked with the valence of participants’ judgements of <em>Incest</em> rather than whether or not it leads to dumbfounding. A key consideration in the <em>Incest</em> scenario is the importance of individual autonomy. Similarly, the items in the HI sub-scale appear to relate to individual autonomy <span class="citation" data-cites="renzhi_key_2013">(e.g., “I rely on myself most of the time; I rarely rely on others,” “I often do ‘my own thing’,” <a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span>. As such it is not surprising that participants who score highly on HI, place higher value on individual autonomy when considering the <em>Incest</em> scenario.</p>
<p>Furthermore, three of the four Vertical Collectivism <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> items specifically relate to the importance of the family. thus providing an indirect measure of the degree to which people value the family unit. Participants who scored higher in VC were more likely to present as dumbfounded than to provide reasons for their judgement of the <em>Incest</em> scenario. It is likely that participants who score higher in VC regard the family as particularly important, and the <em>Incest</em> scenario presents an affront to the family. As such, these participants may perceive the actions of Julile and Mark as a threat to something that they value, but may not be able to articulate this as a reason for their judgement (e.g., it is too abstract, or they do not think it is an “acceptable” reason).</p>
<p>Finally, Meaning in Life: Presence <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span>, was related to responses to the <em>Cannibal</em> scenario, such that participants who scored higher in Meaning in Life: Presence were more likely to provide reasons for their judgements then to present as dumbfounded by <em>Cannibal</em>. Again this is likely due to the specific content, rather than informing the cognitive processes involved. It could be argued that the <em>Cannibal</em> scenario involves considerations about the value of life. Participants who score higher in Meaning in Life: Presence, have given consideration to the meaning (and by extension, value) of life (e.g., “I understand my life’s meaning”). It seems that this reflection life’s meaning may provide people with the necessary justifications/arguments/resources to articulate why they disapprove of <em>Cannibal</em>.</p>
<p>Study 3 did not find any relationship between susceptibility to dumbfounded responding and either ICS <span class="citation" data-cites="renzhi_key_2013">(<a href="#ref-renzhi_key_2013" role="doc-biblioref">Renzhi et al. 2013</a>)</span> or MLQ <span class="citation" data-cites="steger_understanding_2008">(<a href="#ref-steger_understanding_2008" role="doc-biblioref">Steger et al. 2008</a>)</span>. We did find that Vertical Individualilsm predicted selecting “There is nothing wrong” for the <em>Heinz</em> dilemma. The content of the scenario may provide an explanation for this observed relationship. Participants were judging the behaviour of the Druggist, who charged an extremely high price for the drug he developed. The druggest’s behaviour is consistent with individualistic values, and it is not surprising that participants who score higher on this individualism measure endorse the behaviour of the druggist. Study 3 also found that participants who scored higher in Meaning in Life: Search were more likely to be dumbfounded than to provide reasons for their judgement.</p>
</section>
<section id="limitations-and-future-directions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-directions">Limitations and Future directions</h2>
<p>A key limitation in the current studies is the sample make up. Participants in Study 1 were recruited through a Chinese university, participants in Study 2 were university graduates, who also were proficient in English, and participants in Study 3 were also proficient in English, and recruited through snowball sampling in a University setting. This means that none of our samples are representative of their respective population. Furthermore, the samples involved either university graduates, or those currently studying in a university setting, and as such this high level of education is a significant challenge to our stated aim of recruiting from non-WEIRD samples.</p>
<p>The moral foreign language effect <span class="citation" data-cites="cipolletti_moral_2016">(<a href="#ref-cipolletti_moral_2016" role="doc-biblioref">Cipolletti, McFarlane, and Weissglass 2016</a>)</span> means that the use of an English language survey in Studies 2 and 3 is another potential limitation. Previous research has shown that people appear to make more utilitarian judgements when moral scenarios are presented in another language <span class="citation" data-cites="costa_your_2014">(<a href="#ref-costa_your_2014" role="doc-biblioref">Costa et al. 2014</a>)</span>. In the case of the <em>Intuition</em> scenarios, this could potentially lead to a higher number of participants selecting “There is nothing wrong”, rather than presenting as dumbfounded. Despite this potential confound, dumbfounded responding was observed for all scenarios in Studies 2 and 3.</p>
<p>Our studies were not intended as a systematic investigation of cultural differences in evaluation of specific moral content <span class="citation" data-cites="haidt_moral_2008 shweder_big_1997 narvaez_embodied_2016">(there are other research programmes dedicated to this, e.g., <a href="#ref-haidt_moral_2008" role="doc-biblioref">Haidt and Joseph 2008</a>; <a href="#ref-shweder_big_1997" role="doc-biblioref">Shweder et al. 1997</a>; <a href="#ref-narvaez_embodied_2016" role="doc-biblioref">Narvaez 2016</a>)</span>. Here, we applied existing methods in three novel contexts, to assess whether or not moral dumbfounding can be elicited in these under-studied contexts. We found evidence for moral dumbfounding in a Chinese sample, an Indian sample and a mixed sample. Our results provided some evidence for cultural variation (e.g., the relative importance of the death taboo), that may inform the development of future research programmes.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Previous research on moral dumbfounding has exclusively studied WEIRD participants. This poses a challenge to the generalisability of the phenomenon. In three studies we tested whether or not dumbfounded responding could be elicited in non-WEIRD samples. We found evidence for moral dumbfounding in all three samples. Our findings provide some evidence that moral dumbfounding may emerge as a consequence of the nature of moral knowledge - that is, the cognitive processes that underlie the making of moral judgements seem to lead to the emergence of moral dumbfounding in diverse samples. This suggests that further study of the phenomenon, in diverse samples, may provide unique insights into the cognitive mechanisms that govern moral judgements.</p>
</section>
<section id="data-accessibility-statement" class="level1">
<h1>Data Accessibility Statement</h1>
<p>All participant data, and analysis scripts can be found on this paper’s project page on the Open Science Framework at <a href="https://osf.io/2h3k7/">https://osf.io/2h3k7/</a>.</p>
<p>We used R <span class="citation" data-cites="R-base">(Version 4.1.2; <a href="#ref-R-base" role="doc-biblioref">R Core Team 2017</a>)</span> and the R-packages <em>corrplot2021</em> <span class="citation" data-cites="R-corrplot2021">(<a href="#ref-R-corrplot2021" role="doc-biblioref"><strong>R-corrplot2021?</strong></a>)</span>, <em>DescTools</em> <span class="citation" data-cites="R-DescTools">(Version 0.99.47; <a href="#ref-R-DescTools" role="doc-biblioref">Andri et mult. al. 2021</a>)</span>, <em>desnum</em> <span class="citation" data-cites="R-desnum">(Version 0.1.1; <a href="#ref-R-desnum" role="doc-biblioref">McHugh 2017</a>)</span>, <em>dfidx</em> <span class="citation" data-cites="R-dfidx">(Version 0.0.5; <a href="#ref-R-dfidx" role="doc-biblioref">Croissant 2021</a>)</span>, <em>dplyr</em> <span class="citation" data-cites="R-dplyr">(Version 1.1.0; <a href="#ref-R-dplyr" role="doc-biblioref">Wickham et al. 2020</a>)</span>, <em>forcats</em> <span class="citation" data-cites="R-forcats">(Version 1.0.0; <a href="#ref-R-forcats" role="doc-biblioref">Wickham 2020</a>)</span>, <em>foreign</em> <span class="citation" data-cites="R-foreign">(Version 0.8.82; <a href="#ref-R-foreign" role="doc-biblioref">R Core Team 2020</a>)</span>, <em>ggplot2</em> <span class="citation" data-cites="R-ggplot2">(Version 3.4.1; <a href="#ref-R-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span>, <em>ggtext</em> <span class="citation" data-cites="R-ggtext">(Version 0.1.2; <a href="#ref-R-ggtext" role="doc-biblioref"><strong>R-ggtext?</strong></a>)</span>, <em>glue</em> <span class="citation" data-cites="R-glue">(Version 1.6.2; <a href="#ref-R-glue" role="doc-biblioref"><strong>R-glue?</strong></a>)</span>, <em>haven</em> <span class="citation" data-cites="R-haven">(Version 2.5.1; <a href="#ref-R-haven" role="doc-biblioref">Wickham and Miller 2020</a>)</span>, <em>lme4</em> <span class="citation" data-cites="R-lme4">(Version 1.1.31; <a href="#ref-R-lme4" role="doc-biblioref">Bates et al. 2015</a>)</span>, <em>lmerTest</em> <span class="citation" data-cites="R-lmerTest">(Version 3.1.3; <a href="#ref-R-lmerTest" role="doc-biblioref"><strong>R-lmerTest?</strong></a>)</span>, <em>lsr</em> <span class="citation" data-cites="R-lsr">(Version 0.5.2; <a href="#ref-R-lsr" role="doc-biblioref">Navarro 2015</a>)</span>, <em>lubridate</em> <span class="citation" data-cites="R-lubridate">(Version 1.9.2; <a href="#ref-R-lubridate" role="doc-biblioref"><strong>R-lubridate?</strong></a>)</span>, <em>Matrix</em> <span class="citation" data-cites="R-Matrix">(Version 1.5.3; <a href="#ref-R-Matrix" role="doc-biblioref">Bates and Maechler 2021</a>)</span>, <em>mlogit</em> <span class="citation" data-cites="R-mlogit">(Version 1.1.1; <a href="#ref-R-mlogit" role="doc-biblioref">Croissant 2020</a>)</span>, <em>nnet</em> <span class="citation" data-cites="R-nnet">(Version 7.3.17; <a href="#ref-R-nnet" role="doc-biblioref">Venables and Ripley 2002</a>)</span>, <em>papaja</em> <span class="citation" data-cites="R-papaja">(Version 0.1.1.9001; <a href="#ref-R-papaja" role="doc-biblioref">Aust and Barth 2020</a>)</span>, <em>psych</em> <span class="citation" data-cites="R-psych">(Version 2.2.9; <a href="#ref-R-psych" role="doc-biblioref">Revelle 2021</a>)</span>, <em>purrr</em> <span class="citation" data-cites="R-purrr">(Version 1.0.1; <a href="#ref-R-purrr" role="doc-biblioref">Henry and Wickham 2020</a>)</span>, <em>pwr</em> <span class="citation" data-cites="R-pwr">(Version 1.3.0; <a href="#ref-R-pwr" role="doc-biblioref">Champely 2020</a>)</span>, <em>readr</em> <span class="citation" data-cites="R-readr">(Version 2.1.4; <a href="#ref-R-readr" role="doc-biblioref">Wickham and Hester 2021</a>)</span>, <em>readxl</em> <span class="citation" data-cites="R-readxl">(Version 1.4.2; <a href="#ref-R-readxl" role="doc-biblioref">Wickham and Bryan 2019</a>)</span>, <em>reshape2</em> <span class="citation" data-cites="R-reshape2">(Version 1.4.4; <a href="#ref-R-reshape2" role="doc-biblioref">Wickham 2007</a>)</span>, <em>rstatix</em> <span class="citation" data-cites="R-rstatix">(Version 0.7.2; <a href="#ref-R-rstatix" role="doc-biblioref">Kassambara 2020</a>)</span>, <em>scales</em> <span class="citation" data-cites="R-scales">(Version 1.2.1; <a href="#ref-R-scales" role="doc-biblioref">Wickham and Seidel 2020</a>)</span>, <em>stringr</em> <span class="citation" data-cites="R-stringr">(Version 1.5.0; <a href="#ref-R-stringr" role="doc-biblioref">Wickham 2019</a>)</span>, <em>tibble</em> <span class="citation" data-cites="R-tibble">(Version 3.1.8; <a href="#ref-R-tibble" role="doc-biblioref">Müller and Wickham 2021</a>)</span>, <em>tidyr</em> <span class="citation" data-cites="R-tidyr">(Version 1.3.0; <a href="#ref-R-tidyr" role="doc-biblioref">Wickham and Henry 2020</a>)</span>, <em>tidyverse</em> <span class="citation" data-cites="R-tidyverse">(Version 2.0.0; <a href="#ref-R-tidyverse" role="doc-biblioref">Wickham et al. 2019</a>)</span>, and <em>tinylabels</em> <span class="citation" data-cites="R-tinylabels">(Version 0.2.3; <a href="#ref-R-tinylabels" role="doc-biblioref"><strong>R-tinylabels?</strong></a>)</span> for all our analyses.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1">




</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-R-DescTools" class="csl-entry" role="listitem">
Andri et mult. al., Signorell. 2021. <em><span>DescTools</span>: <span>Tools</span> for Descriptive Statistics</em>. Manual.
</div>
<div id="ref-R-papaja" class="csl-entry" role="listitem">
Aust, Frederik, and Marius Barth. 2020. <em><span class="nocase">papaja</span>: <span>Create APA</span> Manuscripts with <span>R Markdown</span></em>. Manual.
</div>
<div id="ref-R-lme4" class="csl-entry" role="listitem">
Bates, Douglas, Martin Mächler, Ben Bolker, and Steve Walker. 2015. <span>“Fitting <span>Linear Mixed-Effects Models Using</span> Lme4.”</span> <em>Journal of Statistical Software</em> 67 (1): 1–48. <a href="https://doi.org/10.18637/jss.v067.i01">https://doi.org/10.18637/jss.v067.i01</a>.
</div>
<div id="ref-R-Matrix" class="csl-entry" role="listitem">
Bates, Douglas, and Martin Maechler. 2021. <em>Matrix: <span>Sparse</span> and Dense Matrix Classes and Methods</em>. Manual.
</div>
<div id="ref-R-pwr" class="csl-entry" role="listitem">
Champely, Stephane. 2020. <em>Pwr: <span>Basic</span> Functions for Power Analysis</em>. Manual.
</div>
<div id="ref-cipolletti_moral_2016" class="csl-entry" role="listitem">
Cipolletti, Heather, Steven McFarlane, and Christine Weissglass. 2016. <span>“The <span>Moral Foreign-Language Effect</span>.”</span> <em>Philosophical Psychology</em> 29 (1): 23–40. <a href="https://doi.org/10.1080/09515089.2014.993063">https://doi.org/10.1080/09515089.2014.993063</a>.
</div>
<div id="ref-costa_your_2014" class="csl-entry" role="listitem">
Costa, Albert, Alice Foucart, Sayuri Hayakawa, Melina Aparici, Jose Apesteguia, Joy Heafner, and Boaz Keysar. 2014. <span>“Your <span>Morals Depend</span> on <span>Language</span>.”</span> <em>PLOS ONE</em> 9 (4): e94842. <a href="https://doi.org/10.1371/journal.pone.0094842">https://doi.org/10.1371/journal.pone.0094842</a>.
</div>
<div id="ref-R-mlogit" class="csl-entry" role="listitem">
Croissant, Yves. 2020. <span>“Estimation of Random Utility Models in <span>R</span>: <span>The</span> <span class="nocase">mlogit</span> Package.”</span> <em>Journal of Statistical Software</em> 95 (11): 1–41. <a href="https://doi.org/10.18637/jss.v095.i11">https://doi.org/10.18637/jss.v095.i11</a>.
</div>
<div id="ref-R-dfidx" class="csl-entry" role="listitem">
———. 2021. <em>Dfidx: <span>Indexed</span> Data Frames</em>. Manual.
</div>
<div id="ref-davis_moral_2015" class="csl-entry" role="listitem">
Davis, Don E., Kenneth Rice, Daryl R. Van Tongeren, Joshua N. Hook, Cirleen DeBlaere, Everett L. Jr. Worthington, and Elise Choe. 2015. <span>“The <span>Moral Foundations Hypothesis Does Not Replicate Well</span> in <span>Black Samples</span>.”</span> <em>Journal of Personality and Social Psychology</em>, September. <a href="https://doi.org/10.1037/pspp0000056">https://doi.org/10.1037/pspp0000056</a>.
</div>
<div id="ref-doris_how_2008" class="csl-entry" role="listitem">
Doris, John M., and Alexandra Plakias. 2008. <span>“How to <span>Argue</span> about <span>Disagreement</span>: <span>Evaluative Diversity</span> and <span>Moral Realism</span>.”</span> In <em>Moral Psychology <span>Volume</span> 2, <span>The</span> Cognitive Science of Morality: Intuition and Diversity</em>, edited by Walter Sinnott-Armstrong, 47–76. <span>London</span>: <span>MIT</span>.
</div>
<div id="ref-dwyer_moral_2009" class="csl-entry" role="listitem">
Dwyer, Susan. 2009. <span>“Moral <span>Dumbfounding</span> and the <span>Linguistic Analogy</span>: <span>Methodological Implications</span> for the <span>Study</span> of <span>Moral Judgment</span>.”</span> <em>Mind &amp; Language</em> 24 (3): 274–96. <a href="https://doi.org/10.1111/j.1468-0017.2009.01363.x">https://doi.org/10.1111/j.1468-0017.2009.01363.x</a>.
</div>
<div id="ref-gray_impure_2015" class="csl-entry" role="listitem">
Gray, Kurt James, and Jonathan E. Keeney. 2015. <span>“Impure or <span>Just Weird</span>? <span>Scenario Sampling Bias Raises Questions About</span> the <span>Foundation</span> of <span>Morality</span>.”</span> <em>Social Psychological and Personality Science</em> 6 (8): 859–68. <a href="https://doi.org/10.1177/1948550615592241">https://doi.org/10.1177/1948550615592241</a>.
</div>
<div id="ref-gray_myth_2014" class="csl-entry" role="listitem">
Gray, Kurt James, Chelsea Schein, and Adrian F. Ward. 2014. <span>“The Myth of Harmless Wrongs in Moral Cognition: <span>Automatic</span> Dyadic Completion from Sin to Suffering.”</span> <em>Journal of Experimental Psychology: General</em> 143 (4): 1600–1615. <a href="https://doi.org/10.1037/a0036149">https://doi.org/10.1037/a0036149</a>.
</div>
<div id="ref-guglielmo_unfounded_2018" class="csl-entry" role="listitem">
Guglielmo, Steve. 2018. <span>“Unfounded Dumbfounding: <span>How</span> Harm and Purity Undermine Evidence for Moral Dumbfounding.”</span> <em>Cognition</em> 170 (January): 334–37. <a href="https://doi.org/10.1016/j.cognition.2017.08.002">https://doi.org/10.1016/j.cognition.2017.08.002</a>.
</div>
<div id="ref-haidt_emotional_2001" class="csl-entry" role="listitem">
Haidt, Jonathan. 2001. <span>“The Emotional Dog and Its Rational Tail: <span>A</span> Social Intuitionist Approach to Moral Judgment.”</span> <em>Psychological Review</em> 108 (4): 814–34. <a href="https://doi.org/10.1037/0033-295X.108.4.814">https://doi.org/10.1037/0033-295X.108.4.814</a>.
</div>
<div id="ref-haidt_moral_2000" class="csl-entry" role="listitem">
Haidt, Jonathan, Fredrik Björklund, and Scott Murphy. 2000. <span>“Moral Dumbfounding: <span>When</span> Intuition Finds No Reason.”</span> <em>Unpublished Manuscript, University of Virginia</em>.
</div>
<div id="ref-haidt_moral_2008" class="csl-entry" role="listitem">
Haidt, Jonathan, and Craig Joseph. 2008. <span>“The Moral Mind: <span>How</span> Five Sets of Innate Intuitions Guide the Development of Many Culture-Specific Virtues, and Perhaps Even Modules.”</span> In <em>The Innate Mind <span>Volume</span> 3: <span>Foundations</span> and the Future.</em>, 367–91. Evolution and Cognition. <span>New York, NY, US</span>: <span>Oxford University Press</span>. <a href="https://doi.org/10.1093/acprof:oso/9780195332834.003.0019">https://doi.org/10.1093/acprof:oso/9780195332834.003.0019</a>.
</div>
<div id="ref-haidt_affect_1993" class="csl-entry" role="listitem">
Haidt, Jonathan, Silvia Helena Koller, and Maria G. Dias. 1993. <span>“Affect, Culture, and Morality, or Is It Wrong to Eat Your Dog?”</span> <em>Journal of Personality and Social Psychology</em> 65 (4): 613–28. <a href="https://doi.org/10.1037/0022-3514.65.4.613">https://doi.org/10.1037/0022-3514.65.4.613</a>.
</div>
<div id="ref-henrich_most_2010" class="csl-entry" role="listitem">
Henrich, Joseph, Steven J. Heine, and Ara Norenzayan. 2010. <span>“Most People Are Not <span>WEIRD</span>.”</span> <em>Nature</em> 466 (7302): 29–29. <a href="https://doi.org/10.1038/466029a">https://doi.org/10.1038/466029a</a>.
</div>
<div id="ref-R-purrr" class="csl-entry" role="listitem">
Henry, Lionel, and Hadley Wickham. 2020. <em>Purrr: <span>Functional</span> Programming Tools</em>. Manual.
</div>
<div id="ref-jacobson_moral_2012" class="csl-entry" role="listitem">
Jacobson, Daniel. 2012. <span>“Moral <span>Dumbfounding</span> and <span>Moral Stupefaction</span>.”</span> In <em>Oxford Studies in Normative Ethics</em>, 2:289.
</div>
<div id="ref-R-rstatix" class="csl-entry" role="listitem">
Kassambara, Alboukadel. 2020. <em>Rstatix: <span class="nocase">Pipe-friendly</span> Framework for Basic Statistical Tests</em>. Manual.
</div>
<div id="ref-li_dimensionality_2007" class="csl-entry" role="listitem">
Li, Fuan, and Lerzan Aksoy. 2007. <span>“Dimensionality of Individualismcollectivism and Measurement Equivalence of <span>Triandis</span> and <span>Gelfand</span>’s Scale.”</span> <em>Journal of Business and Psychology</em> 21 (3): 313–29. <a href="https://doi.org/10.1007/s10869-006-9031-8">https://doi.org/10.1007/s10869-006-9031-8</a>.
</div>
<div id="ref-liberman_psychological_2007" class="csl-entry" role="listitem">
Liberman, Nira, Yaacov Trope, and E. Stephan. 2007. <span>“<span>Psychological distance</span>.”</span> In <em><span>Social Psychology: Handbook of Basic Principles</span></em>, edited by Arie W. Kruglanski and Edward Tory Higgins.
</div>
<div id="ref-machery_evolution_2010" class="csl-entry" role="listitem">
Machery, Edouard, and Ron Mallon. 2010. <span>“Evolution of <span>Morality</span>.”</span> In <em>The <span>Moral Psychology Handbook</span></em>, edited by John M. Doris, 3–46. <span>Oxford; New York</span>: <span>Oxford University Press</span>.
</div>
<div id="ref-R-desnum" class="csl-entry" role="listitem">
McHugh, Cillian. 2017. <em>Desnum: <span>Creates</span> Some Useful Functions</em>. Manual.
</div>
<div id="ref-mchugh_searching_2017a" class="csl-entry" role="listitem">
McHugh, Cillian, Marek McGann, Eric R. Igou, and Elaine L. Kinsella. 2017. <span>“Searching for <span>Moral Dumbfounding</span>: <span>Identifying Measurable Indicators</span> of <span>Moral Dumbfounding</span>.”</span> <em>Collabra: Psychology</em> 3 (1): 1–24. <a href="https://doi.org/10.1525/collabra.79">https://doi.org/10.1525/collabra.79</a>.
</div>
<div id="ref-mchugh_reasons_2020" class="csl-entry" role="listitem">
———. 2020. <span>“Reasons or Rationalizations: <span>The</span> Role of Principles in the Moral Dumbfounding Paradigm.”</span> <em>Journal of Behavioral Decision Making</em> 33 (3): 376–92. <a href="https://doi.org/10.1002/bdm.2167">https://doi.org/10.1002/bdm.2167</a>.
</div>
<div id="ref-R-tibble" class="csl-entry" role="listitem">
Müller, Kirill, and Hadley Wickham. 2021. <em>Tibble: <span>Simple</span> Data Frames</em>. Manual.
</div>
<div id="ref-narvaez_embodied_2016" class="csl-entry" role="listitem">
Narvaez, Darcia. 2016. <em>Embodied <span>Morality</span>: <span>Protectionism</span>, <span>Engagement</span> and <span>Imagination</span></em>. <span>New York, NY</span>: <span>Springer</span>.
</div>
<div id="ref-R-lsr" class="csl-entry" role="listitem">
Navarro, Danielle. 2015. <em>Learning Statistics with <span>R</span>: <span>A</span> Tutorial for Psychology Students and Other Beginners. (<span>Version</span> 0.6)</em>. Manual. <span>Sydney, Australia</span>: <span>University of New South Wales</span>.
</div>
<div id="ref-prinz_morality_2008" class="csl-entry" role="listitem">
Prinz, Jesse J. 2008a. <span>“Is <span>Morality Innate</span>?”</span> In <em>Moral <span>Psychology Volume</span> 1: <span>The</span> Evolution of Morality Adaptations and Innateness</em>. <span>Cambridge, Mass.; London, England</span>: <span>The MIT press</span>.
</div>
<div id="ref-prinz_resisting_2008" class="csl-entry" role="listitem">
———. 2008b. <span>“Resisting the <span>Linguistic Analogy</span>: <span>A Commentary</span> on <span>Hauser</span>, <span>Young</span>, and <span>Cushman</span>.”</span> In <em>Moral Psychology <span>Volume</span> 2, <span>The</span> Cognitive Science of Morality: Intuition and Diversity</em>, edited by Walter Sinnott-Armstrong, 157–70. <span>London</span>: <span>MIT</span>.
</div>
<div id="ref-R-base" class="csl-entry" role="listitem">
R Core Team. 2017. <span>“R: <span>A Language</span> and <span>Environment</span> for <span>Statistical Computing</span>.”</span> <span>Vienna, Austria</span>: <span>R Foundation for Statistical Computing</span>.
</div>
<div id="ref-R-foreign" class="csl-entry" role="listitem">
———. 2020. <em>Foreign: <span>Read</span> Data Stored by ’Minitab’, ’s’, ’<span>SAS</span>’, ’<span>SPSS</span>’, ’Stata’, ’Systat’, ’Weka’, ’<span class="nocase">dBase</span>’, ...</em> Manual.
</div>
<div id="ref-renzhi_key_2013" class="csl-entry" role="listitem">
Renzhi, Huang, Yao Shuqiao, John R. Z. Abela, Fallyn Leibovitch, and Liu Mingfan. 2013. <span>“Key <span>Dimensions</span> and <span>Validity</span> of the <span>Chinese Version</span> of the <span>Individualism-Collectivism Scale</span>.”</span> <em>Chinese Studies</em> 02 (01): 1. <a href="https://doi.org/10.4236/chnstd.2013.21001">https://doi.org/10.4236/chnstd.2013.21001</a>.
</div>
<div id="ref-R-psych" class="csl-entry" role="listitem">
Revelle, William. 2021. <em>Psych: <span>Procedures</span> for Psychological, Psychometric, and Personality Research</em>. Manual. <span>Evanston, Illinois</span>: <span>Northwestern University</span>.
</div>
<div id="ref-royzman_curious_2015" class="csl-entry" role="listitem">
Royzman, Edward B., Kwanwoo Kim, and Robert F. Leeman. 2015. <span>“The Curious Tale of <span>Julie</span> and <span>Mark</span>: <span>Unraveling</span> the Moral Dumbfounding Effect.”</span> <em>Judgment and Decision Making</em> 10 (4): 296–313.
</div>
<div id="ref-selin_death_2019" class="csl-entry" role="listitem">
Selin, Helaine, and Robert M. Rakoff, eds. 2019. <em>Death <span>Across Cultures</span>: <span>Death</span> and <span>Dying</span> in <span>Non-Western Cultures</span></em>. Vol. 9. Science <span>Across Cultures</span>: <span>The History</span> of <span>Non-Western Science</span>. <span>Cham</span>: <span>Springer International Publishing</span>. <a href="https://doi.org/10.1007/978-3-030-18826-9">https://doi.org/10.1007/978-3-030-18826-9</a>.
</div>
<div id="ref-shweder_big_1997" class="csl-entry" role="listitem">
Shweder, Richard A., Nancy C Much, Manomahan Mahapatra, and Lawrence Park. 1997. <span>“The "<span>Big Three</span>" of Morality (Autonomy, Community, Divinity) and the "<span>Big Three</span>" Explanations of Suffering.”</span> In <em>Morality and Health</em>, edited by Allan M. Brandt and Paul Rozin, 119–69. <span>Routledge</span>.
</div>
<div id="ref-sneddon_social_2007" class="csl-entry" role="listitem">
Sneddon, Andrew. 2007. <span>“A <span>Social Model</span> of <span>Moral Dumbfounding</span>: <span>Implications</span> for <span>Studying Moral Reasoning</span> and <span>Moral Judgment</span>.”</span> <em>Philosophical Psychology</em> 20 (6): 731–48. <a href="https://doi.org/10.1080/09515080701694110">https://doi.org/10.1080/09515080701694110</a>.
</div>
<div id="ref-steger_understanding_2008" class="csl-entry" role="listitem">
Steger, Michael F., Todd B. Kashdan, Brandon A. Sullivan, and Danielle Lorentz. 2008. <span>“Understanding the <span>Search</span> for <span>Meaning</span> in <span>Life</span>: <span>Personality</span>, <span>Cognitive Style</span>, and the <span>Dynamic Between Seeking</span> and <span>Experiencing Meaning</span>.”</span> <em>Journal of Personality</em> 76 (2): 199–228. <a href="https://doi.org/10.1111/j.1467-6494.2007.00484.x">https://doi.org/10.1111/j.1467-6494.2007.00484.x</a>.
</div>
<div id="ref-triandis_individualism_2011" class="csl-entry" role="listitem">
Triandis, Harry C., and Michele J. Gelfand. 2011. <span>“Individualism and <span>Collectivism Scale</span>.”</span> <span>American Psychological Association</span>. <a href="https://doi.org/10.1037/t01556-000">https://doi.org/10.1037/t01556-000</a>.
</div>
<div id="ref-vasquez_cultural_2001" class="csl-entry" role="listitem">
Vasquez, Kristin, Dacher Keltner, David H. Ebenbach, and Tracy L. Banaszynski. 2001. <span>“Cultural <span>Variation</span> and <span>Similarity</span> in <span>Moral Rhetorics</span>: <span>Voices</span> from the <span>Philippines</span> and the <span>United States</span>.”</span> <em>Journal of Cross-Cultural Psychology</em> 32 (1): 93–120. <a href="https://doi.org/10.1177/0022022101032001010">https://doi.org/10.1177/0022022101032001010</a>.
</div>
<div id="ref-vasudev_moral_1987" class="csl-entry" role="listitem">
Vasudev, Jyotsna, and Raymond C. Hummel. 1987. <span>“Moral <span>Stage Sequence</span> and <span>Principled Reasoning</span> in an <span>Indian Sample</span>.”</span> <em>Human Development</em> 30 (2): 105–18. <a href="https://doi.org/10.1159/000273170">https://doi.org/10.1159/000273170</a>.
</div>
<div id="ref-R-nnet" class="csl-entry" role="listitem">
Venables, W. N., and B. D. Ripley. 2002. <em>Modern <span>Applied Statistics</span> with <span>S</span></em>. Fourth. <span>New York</span>: <span>Springer</span>.
</div>
<div id="ref-_wenjuanxing_2006" class="csl-entry" role="listitem">
<span>“Wenjuanxing.”</span> 2006. Changsha Ranxing Information Technology Co., Ltd.
</div>
<div id="ref-R-reshape2" class="csl-entry" role="listitem">
Wickham, Hadley. 2007. <span>“Reshaping Data with the <span class="nocase">reshape</span> Package.”</span> <em>Journal of Statistical Software</em> 21 (12): 1–20.
</div>
<div id="ref-R-ggplot2" class="csl-entry" role="listitem">
———. 2016. <em>Ggplot2: <span>Elegant</span> Graphics for Data Analysis</em>. <span>Springer-Verlag New York</span>.
</div>
<div id="ref-R-stringr" class="csl-entry" role="listitem">
———. 2019. <em>Stringr: <span>Simple</span>, Consistent Wrappers for Common String Operations</em>. Manual.
</div>
<div id="ref-R-forcats" class="csl-entry" role="listitem">
———. 2020. <em>Forcats: <span>Tools</span> for Working with Categorical Variables (Factors)</em>. Manual.
</div>
<div id="ref-R-tidyverse" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-R-readxl" class="csl-entry" role="listitem">
Wickham, Hadley, and Jennifer Bryan. 2019. <em>Readxl: <span>Read</span> Excel Files</em>. Manual.
</div>
<div id="ref-R-dplyr" class="csl-entry" role="listitem">
Wickham, Hadley, Romain François, Lionel Henry, and Kirill Müller. 2020. <em>Dplyr: <span>A</span> Grammar of Data Manipulation</em>. Manual.
</div>
<div id="ref-R-tidyr" class="csl-entry" role="listitem">
Wickham, Hadley, and Lionel Henry. 2020. <em>Tidyr: <span>Tidy</span> Messy Data</em>. Manual.
</div>
<div id="ref-R-readr" class="csl-entry" role="listitem">
Wickham, Hadley, and Jim Hester. 2021. <em>Readr: <span>Read</span> Rectangular Text Data</em>. Manual.
</div>
<div id="ref-R-haven" class="csl-entry" role="listitem">
Wickham, Hadley, and Evan Miller. 2020. <em>Haven: <span>Import</span> and Export ’<span>SPSS</span>’, ’Stata’ and ’<span>SAS</span>’ Files</em>. Manual.
</div>
<div id="ref-R-scales" class="csl-entry" role="listitem">
Wickham, Hadley, and Dana Seidel. 2020. <em>Scales: <span>Scale</span> Functions for Visualization</em>. Manual.
</div>
<div id="ref-wielenberg_robust_2014" class="csl-entry" role="listitem">
Wielenberg, Erik J. 2014. <em>Robust <span>Ethics</span>: <span>The Metaphysics</span> and <span>Epistemology</span> of <span>Godless Normative Realism</span></em>. <span>Oxford, United Kingdom</span>: <span>OUP Oxford</span>.
</div>
<div id="ref-wu_cognitive_2011" class="csl-entry" role="listitem">
Wu, Anise M. S., and Lu-sha Lu. 2011. <span>“Cognitive Obstacles Against Organ Donation: <span>The</span> Influence of Negative Attitudes, Norms, and Traditional Beliefs on <span>Chinese</span> People’s Intention to Donate Organs After Death.”</span> <em>Journal of Community &amp; Applied Social Psychology</em> 21 (1): 87–93. <a href="https://doi.org/10.1002/casp.1054">https://doi.org/10.1002/casp.1054</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>One scenario (<em>Incest</em>) depicted an act of consensual sibling incest, using contraception; another (<em>Cannibal</em>) described an act of cannibalism involving a laboratory cadaver due to cremated.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Heinz could not afford drugs priced at 10 times the cost price, and steals drugs to save his wife’s life.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Participants do not articulate or consistently apply harm-based reasons/principles, nor do they articulate norm-based reasons/principles with sufficient consistency to provide evidence that these reasons are guiding their judgements in the dumbfounding paradigm <span class="citation" data-cites="mchugh_reasons_2020">(see <a href="#ref-mchugh_reasons_2020" role="doc-biblioref">McHugh et al. 2020</a>)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>We note that, although not statistically significant, the <em>Cannibal</em> scenario appeared to elicit more dumbfounded responding in the Chinese sample<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><i class="fa-regular fa-copyright" aria-hidden="true"></i> Cillian McHugh, 2023<br> All content licensed under <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-sa" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">(CC BY-NC-SA 4.0)</a></div>   
    <div class="nav-footer-center"><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-hidden="true"></i> and <a href="https://quarto.org/">Quarto</a><br> Inspiration and code snippets taken from <a href="https://github.com/andreashandel/andreashandelwebsite">this site.</a><br> <a href="https://github.com/cillianmiltown/website_quarto">Source at <i class="fa-brands fa-github" aria-hidden="true"></i> GitHub</a></div>
  </div>
</footer>



</body></html>